/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.alejandro.library_systemnuevo;

import Entidades.Enums.rolType;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.*;


/**
 *
 * @author Vkaiido
 */
public class JfrmMenu extends javax.swing.JFrame {

    /**
     * Creates new form JfrmSystemMenu
     */
    public JfrmMenu(rolType rol) {
        initComponents();
        this.setLocationRelativeTo(null);
        userComponent(rol);
        currentPanel = null;
        showJPanel(new JpVentas());
        lblBanner.setIcon(new ImageIcon(imagenBanner.getImage().getScaledInstance(lblBanner.getWidth(), lblBanner.getHeight(), Image.SCALE_SMOOTH)));
        lblBanner.setBackground(btnLibro.getBackground());

        lblLogo.setIcon(new ImageIcon(imagenLogo.getImage().getScaledInstance(lblLogo.getWidth(), lblLogo.getHeight(), Image.SCALE_SMOOTH)));
    }

    final ImageIcon imagenBanner = new ImageIcon(getClass().getResource("/Imagenes/banner.png"));
    final ImageIcon imagenLogo = new ImageIcon(getClass().getResource("/Imagenes/logo.png"));

    @Override
    public Image getIconImage() {

        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("Imagenes/Logo.jpeg"));

        return retValue;
    }
    
    
    private void userComponent(rolType rol){
    
        if(rol==rolType.USUARIO){
        btnUsuarios.setEnabled(false);
        btnCompra.setEnabled(false);
        btnEditoriales.setEnabled(false);
        btnEscritor1.setEnabled(false);
        }
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnLibro = new javax.swing.JButton();
        btnCompra = new javax.swing.JButton();
        btnEditoriales = new javax.swing.JButton();
        btnClientes = new javax.swing.JButton();
        btnVentas = new javax.swing.JButton();
        btnPrestamo = new javax.swing.JButton();
        lblLogo = new javax.swing.JLabel();
        btnLector = new javax.swing.JButton();
        btnEscritor1 = new javax.swing.JButton();
        btnUsuarios = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        lblCerrar = new javax.swing.JLabel();
        lblResizable = new javax.swing.JLabel();
        lblMinimize = new javax.swing.JLabel();
        lblCS = new javax.swing.JLabel();
        JpMain = new javax.swing.JPanel();
        JPBanner = new javax.swing.JPanel();
        lblBanner = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(java.awt.SystemColor.controlHighlight);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(150, 731));

        btnLibro.setBackground(new java.awt.Color(41, 50, 65));
        btnLibro.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        btnLibro.setForeground(new java.awt.Color(255, 255, 255));
        btnLibro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/open-book.png"))); // NOI18N
        btnLibro.setText("Libros");
        btnLibro.setBorder(null);
        btnLibro.setBorderPainted(false);
        btnLibro.setContentAreaFilled(false);
        btnLibro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLibro.setFocusPainted(false);
        btnLibro.setFocusable(false);
        btnLibro.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnLibro.setOpaque(true);
        btnLibro.setRequestFocusEnabled(false);
        btnLibro.setRolloverEnabled(false);
        btnLibro.addHierarchyListener(new java.awt.event.HierarchyListener() {
            public void hierarchyChanged(java.awt.event.HierarchyEvent evt) {
                btnLibroHierarchyChanged(evt);
            }
        });
        btnLibro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnLibroMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnLibroMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnLibroMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnLibroMouseReleased(evt);
            }
        });
        btnLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLibroActionPerformed(evt);
            }
        });

        btnCompra.setBackground(new java.awt.Color(41, 50, 65));
        btnCompra.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        btnCompra.setForeground(new java.awt.Color(255, 255, 255));
        btnCompra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/shopping-cart.png"))); // NOI18N
        btnCompra.setText("Compras");
        btnCompra.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        btnCompra.setBorderPainted(false);
        btnCompra.setContentAreaFilled(false);
        btnCompra.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCompra.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnCompra.setOpaque(true);
        btnCompra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCompraMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCompraMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnCompraMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnCompraMouseReleased(evt);
            }
        });
        btnCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCompraActionPerformed(evt);
            }
        });

        btnEditoriales.setBackground(new java.awt.Color(41, 50, 65));
        btnEditoriales.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        btnEditoriales.setForeground(new java.awt.Color(255, 255, 255));
        btnEditoriales.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/bookhouse.png"))); // NOI18N
        btnEditoriales.setText("Editoriales");
        btnEditoriales.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        btnEditoriales.setBorderPainted(false);
        btnEditoriales.setContentAreaFilled(false);
        btnEditoriales.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEditoriales.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnEditoriales.setOpaque(true);
        btnEditoriales.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnEditorialesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnEditorialesMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnEditorialesMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnEditorialesMouseReleased(evt);
            }
        });
        btnEditoriales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditorialesActionPerformed(evt);
            }
        });

        btnClientes.setBackground(new java.awt.Color(41, 50, 65));
        btnClientes.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        btnClientes.setForeground(new java.awt.Color(255, 255, 255));
        btnClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/client.png"))); // NOI18N
        btnClientes.setText("Clientes");
        btnClientes.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        btnClientes.setBorderPainted(false);
        btnClientes.setContentAreaFilled(false);
        btnClientes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnClientes.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnClientes.setOpaque(true);
        btnClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnClientesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnClientesMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnClientesMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnClientesMouseReleased(evt);
            }
        });
        btnClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClientesActionPerformed(evt);
            }
        });

        btnVentas.setBackground(new java.awt.Color(41, 50, 65));
        btnVentas.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        btnVentas.setForeground(new java.awt.Color(255, 255, 255));
        btnVentas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/best-price.png"))); // NOI18N
        btnVentas.setText("Ventas");
        btnVentas.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        btnVentas.setBorderPainted(false);
        btnVentas.setContentAreaFilled(false);
        btnVentas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnVentas.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnVentas.setOpaque(true);
        btnVentas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnVentasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnVentasMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnVentasMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnVentasMouseReleased(evt);
            }
        });
        btnVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVentasActionPerformed(evt);
            }
        });

        btnPrestamo.setBackground(new java.awt.Color(41, 50, 65));
        btnPrestamo.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        btnPrestamo.setForeground(new java.awt.Color(255, 255, 255));
        btnPrestamo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/contract.png"))); // NOI18N
        btnPrestamo.setText("Prestamos");
        btnPrestamo.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        btnPrestamo.setBorderPainted(false);
        btnPrestamo.setContentAreaFilled(false);
        btnPrestamo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPrestamo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnPrestamo.setOpaque(true);
        btnPrestamo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnPrestamoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnPrestamoMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnPrestamoMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnPrestamoMouseReleased(evt);
            }
        });
        btnPrestamo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrestamoActionPerformed(evt);
            }
        });

        btnLector.setBackground(new java.awt.Color(41, 50, 65));
        btnLector.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        btnLector.setForeground(new java.awt.Color(255, 255, 255));
        btnLector.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/study.png"))); // NOI18N
        btnLector.setText("Lectores");
        btnLector.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        btnLector.setBorderPainted(false);
        btnLector.setContentAreaFilled(false);
        btnLector.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLector.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnLector.setOpaque(true);
        btnLector.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnLectorMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnLectorMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnLectorMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnLectorMouseReleased(evt);
            }
        });
        btnLector.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLectorActionPerformed(evt);
            }
        });

        btnEscritor1.setBackground(new java.awt.Color(41, 50, 65));
        btnEscritor1.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        btnEscritor1.setForeground(new java.awt.Color(255, 255, 255));
        btnEscritor1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/writer.png"))); // NOI18N
        btnEscritor1.setText("Escritores");
        btnEscritor1.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        btnEscritor1.setBorderPainted(false);
        btnEscritor1.setContentAreaFilled(false);
        btnEscritor1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEscritor1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnEscritor1.setOpaque(true);
        btnEscritor1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnEscritor1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnEscritor1MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnEscritor1MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnEscritor1MouseReleased(evt);
            }
        });
        btnEscritor1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEscritor1ActionPerformed(evt);
            }
        });

        btnUsuarios.setBackground(new java.awt.Color(41, 50, 65));
        btnUsuarios.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        btnUsuarios.setForeground(new java.awt.Color(255, 255, 255));
        btnUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/skills.png"))); // NOI18N
        btnUsuarios.setText("Usuarios");
        btnUsuarios.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        btnUsuarios.setBorderPainted(false);
        btnUsuarios.setContentAreaFilled(false);
        btnUsuarios.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnUsuarios.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnUsuarios.setOpaque(true);
        btnUsuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnUsuariosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnUsuariosMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnUsuariosMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnUsuariosMouseReleased(evt);
            }
        });
        btnUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUsuariosActionPerformed(evt);
            }
        });

        jPanel2.setPreferredSize(new java.awt.Dimension(0, 25));

        lblCerrar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblCerrar.setForeground(new java.awt.Color(255, 0, 0));
        lblCerrar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cancel.png"))); // NOI18N
        lblCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCerrarMouseClicked(evt);
            }
        });

        lblResizable.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblResizable.setForeground(new java.awt.Color(255, 0, 0));
        lblResizable.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblResizable.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/maximize.png"))); // NOI18N
        lblResizable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblResizableMouseClicked(evt);
            }
        });

        lblMinimize.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblMinimize.setForeground(new java.awt.Color(255, 0, 0));
        lblMinimize.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMinimize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/minus-button.png"))); // NOI18N
        lblMinimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMinimizeMouseClicked(evt);
            }
        });

        lblCS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/log_out.png"))); // NOI18N
        lblCS.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblCS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCSMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(lblCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(lblResizable, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(lblMinimize, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblCS, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblResizable, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMinimize, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addComponent(lblCS, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnCompra, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnEditoriales, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE)
            .addComponent(btnClientes, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnVentas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnLector, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnPrestamo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnEscritor1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnUsuarios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lblLogo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE)
            .addComponent(btnLibro, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblLogo, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(btnLibro, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addComponent(btnCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addComponent(btnEditoriales, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addComponent(btnClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addComponent(btnVentas, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addComponent(btnLector, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addComponent(btnPrestamo, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addComponent(btnEscritor1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(btnUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        JpMain.setBackground(new java.awt.Color(255, 255, 255));
        JpMain.setPreferredSize(new java.awt.Dimension(1050, 540));
        JpMain.setRequestFocusEnabled(false);
        JpMain.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                JpMainComponentResized(evt);
            }
        });

        javax.swing.GroupLayout JpMainLayout = new javax.swing.GroupLayout(JpMain);
        JpMain.setLayout(JpMainLayout);
        JpMainLayout.setHorizontalGroup(
            JpMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1064, Short.MAX_VALUE)
        );
        JpMainLayout.setVerticalGroup(
            JpMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 527, Short.MAX_VALUE)
        );

        JPBanner.setBackground(new java.awt.Color(41, 50, 65));
        JPBanner.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                JPBannerMouseDragged(evt);
            }
        });

        lblBanner.setBackground(new java.awt.Color(41, 50, 65));
        lblBanner.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBanner.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblBanner.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                lblBannerMouseDragged(evt);
            }
        });

        javax.swing.GroupLayout JPBannerLayout = new javax.swing.GroupLayout(JPBanner);
        JPBanner.setLayout(JPBannerLayout);
        JPBannerLayout.setHorizontalGroup(
            JPBannerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblBanner, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        JPBannerLayout.setVerticalGroup(
            JPBannerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblBanner, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JpMain, javax.swing.GroupLayout.DEFAULT_SIZE, 1064, Short.MAX_VALUE)
                    .addComponent(JPBanner, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(JPBanner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JpMain, javax.swing.GroupLayout.DEFAULT_SIZE, 527, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 746, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    JPanel currentPanel;

    public void showJPanel(JPanel form) {
        //currentPanel = null;
        if (currentPanel == null) {

            currentPanel = form;
            //form.setLocation(0,0);
            JpMain.removeAll();
            form.setSize(JpMain.getWidth(), JpMain.getHeight());

            JpMain.add(form, BorderLayout.CENTER);
            JpMain.revalidate();
            JpMain.repaint();

        }
    }

    private void btnLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLibroActionPerformed
        currentPanel = null;
        showJPanel(new JpLibro(formMain));
    }//GEN-LAST:event_btnLibroActionPerformed

    private void btnClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClientesActionPerformed

        currentPanel = null;
        showJPanel(new JpClientes());
    }//GEN-LAST:event_btnClientesActionPerformed


    private void JpMainComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_JpMainComponentResized
        if (currentPanel != null) {

            JpMain.removeAll();
            currentPanel.setSize(JpMain.getWidth(), JpMain.getHeight());

            JpMain.add(currentPanel, BorderLayout.CENTER);
            JpMain.revalidate();
            JpMain.repaint();
            //System.out.println(JpMain.getWidth()+" "+JpMain.getHeight());       
        }


    }//GEN-LAST:event_JpMainComponentResized
    JfrmMenu formMain = this;
    private void btnEscritor1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEscritor1ActionPerformed
        currentPanel = null;
        showJPanel(new JpEscritor(formMain));
    }//GEN-LAST:event_btnEscritor1ActionPerformed

    private void btnPrestamoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrestamoActionPerformed
        currentPanel = null;
        showJPanel(new JpPrestamo());
    }//GEN-LAST:event_btnPrestamoActionPerformed

    private void btnLectorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLectorActionPerformed
        currentPanel = null;
        showJPanel(new JpLector());
    }//GEN-LAST:event_btnLectorActionPerformed

    private void btnVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVentasActionPerformed
        currentPanel = null;
        showJPanel(new JpVentas());
    }//GEN-LAST:event_btnVentasActionPerformed

    private void btnEditorialesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditorialesActionPerformed
        currentPanel = null;
        showJPanel(new JpEditorial());
    }//GEN-LAST:event_btnEditorialesActionPerformed

    private void btnCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCompraActionPerformed
        currentPanel = null;
        showJPanel(new JpCompra());
    }//GEN-LAST:event_btnCompraActionPerformed

    private void btnUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsuariosActionPerformed
        /*JfrmRegistro frm= new JfrmRegistro();
        frm.setVisible(true);
        this.dispose();*/
        currentPanel = null;
        showJPanel(new JpUsuario());
    }//GEN-LAST:event_btnUsuariosActionPerformed

    private void btnLibroHierarchyChanged(java.awt.event.HierarchyEvent evt) {//GEN-FIRST:event_btnLibroHierarchyChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLibroHierarchyChanged

    private void lblCerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCerrarMouseClicked
        System.exit(0);
    }//GEN-LAST:event_lblCerrarMouseClicked

    private void lblMinimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMinimizeMouseClicked
        this.setState(1);
    }//GEN-LAST:event_lblMinimizeMouseClicked

    private void lblResizableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblResizableMouseClicked
        if (this.getExtendedState() == 6) {
            this.setExtendedState(0);
        } else {
            this.setExtendedState(6);

        }
    }//GEN-LAST:event_lblResizableMouseClicked

    private int x;
    private int y;

    private void lblBannerMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBannerMouseDragged

    }//GEN-LAST:event_lblBannerMouseDragged

    private void JPBannerMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JPBannerMouseDragged
        x = evt.getX();
        y = evt.getY();

        this.setLocation(evt.getXOnScreen() - x, evt.getYOnScreen() - y);
    }//GEN-LAST:event_JPBannerMouseDragged

    private void btnLibroMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLibroMouseEntered
        btnLibro.setBackground(new Color(75, 163, 252));

    }//GEN-LAST:event_btnLibroMouseEntered

    private void btnLibroMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLibroMouseExited
        btnLibro.setBackground(new Color(41, 50, 65));
    }//GEN-LAST:event_btnLibroMouseExited

    private void btnLibroMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLibroMousePressed
        btnLibro.setBackground(new Color(41, 50, 65));
    }//GEN-LAST:event_btnLibroMousePressed

    private void btnLibroMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLibroMouseReleased
        btnLibro.setBackground(new Color(75, 163, 252));
    }//GEN-LAST:event_btnLibroMouseReleased


    private void btnCompraMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCompraMouseEntered
        btnCompra.setBackground(new Color(75, 163, 252));
    }//GEN-LAST:event_btnCompraMouseEntered

    private void btnCompraMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCompraMouseExited
        btnCompra.setBackground(new Color(41, 50, 65));
    }//GEN-LAST:event_btnCompraMouseExited

    private void btnCompraMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCompraMousePressed
        btnCompra.setBackground(new Color(41, 50, 65));
    }//GEN-LAST:event_btnCompraMousePressed

    private void btnCompraMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCompraMouseReleased
        btnCompra.setBackground(new Color(75, 163, 252));
    }//GEN-LAST:event_btnCompraMouseReleased


    private void btnEditorialesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditorialesMouseEntered
        btnEditoriales.setBackground(new Color(75, 163, 252));
    }//GEN-LAST:event_btnEditorialesMouseEntered

    private void btnEditorialesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditorialesMouseExited
        btnEditoriales.setBackground(new Color(41, 50, 65));
    }//GEN-LAST:event_btnEditorialesMouseExited

    private void btnEditorialesMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditorialesMousePressed
        btnEditoriales.setBackground(new Color(41, 50, 65));
    }//GEN-LAST:event_btnEditorialesMousePressed

    private void btnEditorialesMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditorialesMouseReleased
        btnEditoriales.setBackground(new Color(75, 163, 252));
    }//GEN-LAST:event_btnEditorialesMouseReleased


    private void btnClientesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClientesMouseEntered
        btnClientes.setBackground(new Color(75, 163, 252));
    }//GEN-LAST:event_btnClientesMouseEntered

    private void btnClientesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClientesMouseExited
        btnClientes.setBackground(new Color(41, 50, 65));
    }//GEN-LAST:event_btnClientesMouseExited

    private void btnClientesMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClientesMousePressed
        btnClientes.setBackground(new Color(41, 50, 65));
    }//GEN-LAST:event_btnClientesMousePressed

    private void btnClientesMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClientesMouseReleased
        btnClientes.setBackground(new Color(75, 163, 252));
    }//GEN-LAST:event_btnClientesMouseReleased


    private void btnVentasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVentasMouseEntered
        btnVentas.setBackground(new Color(75, 163, 252));
    }//GEN-LAST:event_btnVentasMouseEntered

    private void btnVentasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVentasMouseExited
        btnVentas.setBackground(new Color(41, 50, 65));
    }//GEN-LAST:event_btnVentasMouseExited

    private void btnVentasMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVentasMousePressed
        btnVentas.setBackground(new Color(41, 50, 65));
    }//GEN-LAST:event_btnVentasMousePressed

    private void btnVentasMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVentasMouseReleased
        btnVentas.setBackground(new Color(75, 163, 252));
    }//GEN-LAST:event_btnVentasMouseReleased


    private void btnLectorMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLectorMouseEntered
        btnLector.setBackground(new Color(75, 163, 252));
    }//GEN-LAST:event_btnLectorMouseEntered

    private void btnLectorMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLectorMouseExited
        btnLector.setBackground(new Color(41, 50, 65));
    }//GEN-LAST:event_btnLectorMouseExited

    private void btnLectorMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLectorMousePressed
        btnLector.setBackground(new Color(41, 50, 65));
    }//GEN-LAST:event_btnLectorMousePressed

    private void btnLectorMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLectorMouseReleased
        btnLector.setBackground(new Color(75, 163, 252));
    }//GEN-LAST:event_btnLectorMouseReleased


    private void btnPrestamoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPrestamoMouseEntered
        btnPrestamo.setBackground(new Color(75, 163, 252));
    }//GEN-LAST:event_btnPrestamoMouseEntered

    private void btnPrestamoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPrestamoMouseExited
        btnPrestamo.setBackground(new Color(41, 50, 65));
    }//GEN-LAST:event_btnPrestamoMouseExited

    private void btnPrestamoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPrestamoMousePressed
        btnPrestamo.setBackground(new Color(41, 50, 65));
    }//GEN-LAST:event_btnPrestamoMousePressed

    private void btnPrestamoMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPrestamoMouseReleased
        btnPrestamo.setBackground(new Color(75, 163, 252));
    }//GEN-LAST:event_btnPrestamoMouseReleased

    private void btnEscritor1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEscritor1MouseEntered
        btnEscritor1.setBackground(new Color(75, 163, 252));
    }//GEN-LAST:event_btnEscritor1MouseEntered

    private void btnEscritor1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEscritor1MouseExited
        btnEscritor1.setBackground(new Color(41, 50, 65));
    }//GEN-LAST:event_btnEscritor1MouseExited

    private void btnEscritor1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEscritor1MousePressed
        btnEscritor1.setBackground(new Color(41, 50, 65));
    }//GEN-LAST:event_btnEscritor1MousePressed

    private void btnEscritor1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEscritor1MouseReleased
        btnEscritor1.setBackground(new Color(75, 163, 252));
    }//GEN-LAST:event_btnEscritor1MouseReleased

    private void btnUsuariosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUsuariosMouseEntered
        btnUsuarios.setBackground(new Color(75, 163, 252));
    }//GEN-LAST:event_btnUsuariosMouseEntered

    private void btnUsuariosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUsuariosMouseExited
        btnUsuarios.setBackground(new Color(41, 50, 65));
    }//GEN-LAST:event_btnUsuariosMouseExited

    private void btnUsuariosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUsuariosMousePressed
        btnUsuarios.setBackground(new Color(41, 50, 65));
    }//GEN-LAST:event_btnUsuariosMousePressed

    private void btnUsuariosMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUsuariosMouseReleased
        btnUsuarios.setBackground(new Color(75, 163, 252));
    }//GEN-LAST:event_btnUsuariosMouseReleased

    private void lblCSMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCSMouseClicked
  
        this.dispose();
        FrmLogin abrir = new FrmLogin();
            abrir.setVisible(true);
    }//GEN-LAST:event_lblCSMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(rolType rol) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JfrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JfrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JfrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JfrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JfrmMenu(rol).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JPBanner;
    private javax.swing.JPanel JpMain;
    private javax.swing.JButton btnClientes;
    private javax.swing.JButton btnCompra;
    private javax.swing.JButton btnEditoriales;
    private javax.swing.JButton btnEscritor1;
    private javax.swing.JButton btnLector;
    private javax.swing.JButton btnLibro;
    private javax.swing.JButton btnPrestamo;
    private javax.swing.JButton btnUsuarios;
    private javax.swing.JButton btnVentas;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblBanner;
    private javax.swing.JLabel lblCS;
    private javax.swing.JLabel lblCerrar;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblMinimize;
    private javax.swing.JLabel lblResizable;
    // End of variables declaration//GEN-END:variables
}
