/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.alejandro.library_systemnuevo;

import DAO.*;
import Entidades.*;
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import utilidades.GestionColumnas;
import utilidades.GestionEncabezadoTabla;

/**
 *
 * @author Vkaiido
 */
public class JpCompra extends javax.swing.JPanel {

    DefaultTableModel model = new DefaultTableModel();
    //DecimalFormat formato=new DecimalFormat("#.##");
    Date fecha = new Date();
    //int IdEditorial[];
    //int IdLibro[];
    //int librofk;

    /**
     * Creates new form JpCompra
     */
    public JpCompra() {
        initComponents();
        txtNumeroDoc.setText("21112000");
        fecha = Calendar.getInstance().getTime();
        //FiltroCliente(Busqueda);
        jdcFecha.setDate(fecha);
        initId();
        tblCompra.getColumnModel().getColumn(1).setPreferredWidth(250);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        txtCCliente = new javax.swing.JLabel();
        btnME = new javax.swing.JButton();
        txtCCliente1 = new javax.swing.JLabel();
        txtCodigoEdit = new javax.swing.JTextField();
        txtCCliente2 = new javax.swing.JLabel();
        btnML = new javax.swing.JButton();
        txtCCliente3 = new javax.swing.JLabel();
        txtLibro = new javax.swing.JTextField();
        txtCCliente4 = new javax.swing.JLabel();
        txtPrecio = new javax.swing.JTextField();
        txtCCliente5 = new javax.swing.JLabel();
        txtCant = new javax.swing.JTextField();
        txtCCliente6 = new javax.swing.JLabel();
        txtPV = new javax.swing.JTextField();
        txtCCliente7 = new javax.swing.JLabel();
        jdcFecha = new com.toedter.calendar.JDateChooser();
        txtCCliente9 = new javax.swing.JLabel();
        txtCCliente10 = new javax.swing.JLabel();
        txtclib = new javax.swing.JTextField();
        txtEdit1 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtNumeroDoc = new javax.swing.JTextField();
        txtIDCOMPRA = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        btnLibro1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCompra = new javax.swing.JTable();
        BtnCancelar = new javax.swing.JButton();
        btnAgregarCompra = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtTotal = new javax.swing.JTextField();
        txtImpuesto = new javax.swing.JTextField();
        btnADD = new javax.swing.JButton();
        BtnBorrar = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        txtCCliente.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        txtCCliente.setText("EDITORIAL:");

        btnME.setBackground(new java.awt.Color(41, 50, 65));
        btnME.setForeground(new java.awt.Color(255, 255, 255));
        btnME.setText("Buscar");
        btnME.setContentAreaFilled(false);
        btnME.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnME.setOpaque(true);
        btnME.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnMEMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnMEMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnMEMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnMEMouseReleased(evt);
            }
        });
        btnME.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMEActionPerformed(evt);
            }
        });

        txtCCliente1.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        txtCCliente1.setText("CODIGO EDITORIAL");

        txtCodigoEdit.setEditable(false);
        txtCodigoEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodigoEditActionPerformed(evt);
            }
        });

        txtCCliente2.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        txtCCliente2.setText("CODIGO LIBRO");

        btnML.setBackground(new java.awt.Color(41, 50, 65));
        btnML.setForeground(new java.awt.Color(255, 255, 255));
        btnML.setText("Buscar");
        btnML.setContentAreaFilled(false);
        btnML.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnML.setOpaque(true);
        btnML.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnMLMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnMLMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnMLMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnMLMouseReleased(evt);
            }
        });
        btnML.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMLActionPerformed(evt);
            }
        });

        txtCCliente3.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        txtCCliente3.setText("LIBRO:");

        txtLibro.setEditable(false);

        txtCCliente4.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        txtCCliente4.setText("PRECIO COMPRA:");

        txtPrecio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPrecioKeyTyped(evt);
            }
        });

        txtCCliente5.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        txtCCliente5.setText("CANTIDAD:");
        txtCCliente5.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        txtCant.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCantKeyTyped(evt);
            }
        });

        txtCCliente6.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        txtCCliente6.setText("PRECIO VENTA:");
        txtCCliente6.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        txtPV.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPVKeyTyped(evt);
            }
        });

        txtCCliente7.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        txtCCliente7.setText("FECHA:");
        txtCCliente7.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        txtCCliente9.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        txtCCliente9.setText("$");

        txtCCliente10.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        txtCCliente10.setText("$");

        txtclib.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtclibActionPerformed(evt);
            }
        });
        txtclib.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtclibKeyPressed(evt);
            }
        });

        txtEdit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEdit1ActionPerformed(evt);
            }
        });
        txtEdit1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtEdit1KeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtCCliente2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtCCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtCCliente4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(txtCCliente9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(txtCCliente5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCant, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCCliente6))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtEdit1, javax.swing.GroupLayout.DEFAULT_SIZE, 273, Short.MAX_VALUE)
                            .addComponent(txtclib))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnME, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnML, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addGap(12, 12, 12)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(txtCCliente10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPV, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(txtCCliente3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtCCliente1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(0, 0, 0)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(txtCCliente7, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jdcFecha, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE))
                    .addComponent(txtLibro)
                    .addComponent(txtCodigoEdit))
                .addContainerGap(102, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnME)
                    .addComponent(txtCCliente1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCodigoEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEdit1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCCliente2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnML)
                            .addComponent(txtCCliente3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtLibro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtclib, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtCCliente4, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtPV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtCCliente6, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtCant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtCCliente5, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtCCliente7, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtCCliente9)
                        .addComponent(txtCCliente10))
                    .addComponent(jdcFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1050, 100));

        jLabel1.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("La casa del libro");

        jLabel3.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        jLabel4.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Numero de documento");

        txtNumeroDoc.setEditable(false);

        txtIDCOMPRA.setEditable(false);

        jLabel7.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Factura No");

        btnLibro1.setBackground(new java.awt.Color(153, 153, 153));
        btnLibro1.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        btnLibro1.setForeground(new java.awt.Color(255, 255, 255));
        btnLibro1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/reporte-de-negocios (2).png"))); // NOI18N
        btnLibro1.setBorder(null);
        btnLibro1.setBorderPainted(false);
        btnLibro1.setContentAreaFilled(false);
        btnLibro1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLibro1.setFocusPainted(false);
        btnLibro1.setFocusable(false);
        btnLibro1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnLibro1.setOpaque(true);
        btnLibro1.setRequestFocusEnabled(false);
        btnLibro1.setRolloverEnabled(false);
        btnLibro1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLibro1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(195, 195, 195))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(326, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNumeroDoc, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtIDCOMPRA, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(526, 526, 526))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnLibro1)
                        .addGap(163, 163, 163))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNumeroDoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnLibro1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtIDCOMPRA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addGap(24, 24, 24)))
                .addGap(29, 29, 29))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        tblCompra.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id_Libro", "Libro", "Cantidad", "Precio", "Precio_Venta", "impuesto", "Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblCompra.setPreferredSize(new java.awt.Dimension(1030, 240));
        tblCompra.addHierarchyListener(new java.awt.event.HierarchyListener() {
            public void hierarchyChanged(java.awt.event.HierarchyEvent evt) {
                tblCompraHierarchyChanged(evt);
            }
        });
        jScrollPane1.setViewportView(tblCompra);

        BtnCancelar.setBackground(new java.awt.Color(255, 51, 51));
        BtnCancelar.setForeground(new java.awt.Color(255, 255, 255));
        BtnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/error.png"))); // NOI18N
        BtnCancelar.setText("Cancelar Compra");
        BtnCancelar.setContentAreaFilled(false);
        BtnCancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnCancelar.setOpaque(true);
        BtnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCancelarActionPerformed(evt);
            }
        });

        btnAgregarCompra.setBackground(new java.awt.Color(0, 153, 51));
        btnAgregarCompra.setForeground(new java.awt.Color(255, 255, 255));
        btnAgregarCompra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cashier-machine.png"))); // NOI18N
        btnAgregarCompra.setText("Agregar Compra");
        btnAgregarCompra.setContentAreaFilled(false);
        btnAgregarCompra.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAgregarCompra.setOpaque(true);
        btnAgregarCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarCompraActionPerformed(evt);
            }
        });

        jLabel5.setText("Impuesto");

        jLabel6.setText("Total");

        txtTotal.setEditable(false);

        txtImpuesto.setEditable(false);
        txtImpuesto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtImpuestoActionPerformed(evt);
            }
        });

        btnADD.setBackground(new java.awt.Color(0, 153, 51));
        btnADD.setForeground(new java.awt.Color(255, 255, 255));
        btnADD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/addlbr.png"))); // NOI18N
        btnADD.setText("Agregar Libro");
        btnADD.setContentAreaFilled(false);
        btnADD.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnADD.setOpaque(true);
        btnADD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnADDActionPerformed(evt);
            }
        });

        BtnBorrar.setBackground(new java.awt.Color(255, 51, 51));
        BtnBorrar.setForeground(new java.awt.Color(255, 255, 255));
        BtnBorrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/delLib.png"))); // NOI18N
        BtnBorrar.setText("Eliminar Libro");
        BtnBorrar.setContentAreaFilled(false);
        BtnBorrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnBorrar.setOpaque(true);
        BtnBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBorrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(btnAgregarCompra)
                        .addGap(50, 50, 50)
                        .addComponent(BtnCancelar)
                        .addGap(382, 382, 382)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtImpuesto, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtTotal))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1003, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(btnADD)
                        .addGap(50, 50, 50)
                        .addComponent(BtnBorrar)))
                .addGap(39, 39, 39))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnADD)
                    .addComponent(BtnBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtImpuesto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnAgregarCompra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BtnCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1217, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void initId() {
        ComprasDAO vt = new ComprasDAO();
        int ID = vt.idCompra();
        txtIDCOMPRA.setText(String.valueOf(ID + 1));

    }



    private void limpiar() {
        txtCodigoEdit.setText("");
        txtPrecio.setText("");
        txtCant.setText("");
        txtPV.setText("");
        txtImpuesto.setText("");
        txtTotal.setText("");
        txtclib.setText("");
        txtEdit1.setText("");
       
        txtLibro.setText("");

    }

   

    private double redondear(double num) {
        return Math.rint(num * 100) / 100;
    }

    void calcularTotal() {

        double subtotal = 0;
        double sumaImpuesto = 0;
        for (int i = 0; i < tblCompra.getRowCount(); i++) {

            double impuesto = Double.parseDouble(tblCompra.getValueAt(i, 5).toString());
            double total = Double.parseDouble(tblCompra.getValueAt(i, 6).toString());
            sumaImpuesto += impuesto;
            subtotal += total;

        }

        txtImpuesto.setText(String.valueOf(redondear(sumaImpuesto)));
        double total = subtotal + sumaImpuesto;
        txtTotal.setText(String.valueOf(redondear(total)));
    }

    private void guardarCompra() {

        Compras compras = new Compras();
        ComprasDAO comprasDAO = new ComprasDAO();

        compras.setIdEditorial(ided);
        compras.setFechaCompra(fecha);
        compras.setNumeroComprobante(txtNumeroDoc.getText());
        compras.setIdCompra(Integer.parseInt(txtIDCOMPRA.getText()));

        comprasDAO.addCompras(compras);

    }

    private void guardarDetalle() {
        DetalleCompras dtc = new DetalleCompras();
        ComprasDAO comprasDAO = new ComprasDAO();

        int IDCOMPRA = Integer.parseInt(txtIDCOMPRA.getText());
        for (int i = 0; i < tblCompra.getRowCount(); i++) {
            dtc.setIdCompra(IDCOMPRA);
            dtc.setIdlibro(Integer.parseInt(tblCompra.getValueAt(i, 0).toString()));
            dtc.setCantidadCompra(Integer.parseInt(tblCompra.getValueAt(i, 2).toString()));
            dtc.setPrecioCompra(Double.parseDouble(tblCompra.getValueAt(i, 3).toString()));
            dtc.setPrecioVenta(Double.parseDouble(tblCompra.getValueAt(i, 4).toString()));          
            dtc.setImpuestoCompra(Double.parseDouble(tblCompra.getValueAt(i, 5).toString()));

            comprasDAO.addDetalleCompra(dtc);

        }
        //JOptionPane.showMessageDialog(null, "detalle de ventas agregadas");
    }

    private void eliminar() {
        int fil;
        if (model.getRowCount() > 0) {
            if (tblCompra.getSelectedRow() != -1) {
                fil = tblCompra.getSelectedRow();
                model.removeRow(fil);
                calcularTotal();
            } else {
                JOptionPane.showMessageDialog(null, "Seleccione Una Fila");
            }
        } else {
            JOptionPane.showMessageDialog(null, "No hay Filas en la Tabla");
        }
    }

    private void btnAgregarCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarCompraActionPerformed

        if (ided != 0 && idlb != 0) {
if (tblCompra.getRowCount() == 0) {
        
        JOptionPane.showMessageDialog(null, "No ha ingresado ningún libro", "Advertencia", JOptionPane.WARNING_MESSAGE);
        return; 
    }else{
            guardarCompra();
            guardarDetalle();
            limpiar();
            clearTable();
        } }else {
            JOptionPane.showMessageDialog(null, "Llene todos los campos");
        }

    }//GEN-LAST:event_btnAgregarCompraActionPerformed

    private void txtImpuestoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtImpuestoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtImpuestoActionPerformed


    private void btnADDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnADDActionPerformed

        if (txtPrecio.getText().equals("") || txtCant.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Llene todos los campos");

        } else {

            if (txtPV.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "El articulo seleccionado no tiene precio de venta");

            } else {
                if (Double.parseDouble(txtPV.getText()) > 0) {

                    model = (DefaultTableModel) tblCompra.getModel();
                    String rowData[] = new String[7];
                    //rowData[0] = cmbLibro.getSelectedItem().toString();

                    rowData[0] = String.valueOf(idlb);
                    rowData[1] = txtLibro.getText();
                    rowData[2] = txtCant.getText();
                    rowData[3] = txtPrecio.getText();
                    rowData[4] = txtPV.getText();
                    int cantidad = Integer.parseInt(txtCant.getText());
                    double precio = Double.parseDouble(txtPrecio.getText());
                    double precio_Venta = Double.parseDouble(txtPV.getText());
                    double totallb = cantidad * precio;
                    rowData[5] = String.valueOf(redondear(totallb * 0.13));
                    rowData[6] = String.valueOf(redondear(totallb));
                    /*rowData[4] = txtFechaVenta.getText();*/
                    model.addRow(rowData);
                    //tblVenta.getColumnModel().getColumn(0)

                    calcularTotal();
                } else {

                    JOptionPane.showMessageDialog(null, "No puede vender el producto a 0 dolares");
                }

            }
        }

    }//GEN-LAST:event_btnADDActionPerformed

    
    private void clearTable(){
tblCompra.selectAll();
        int filas[] = tblCompra.getSelectedRows();
        int indice = filas.length - 1;
        for (int i = 0; i < filas.length; i++) {
            model.removeRow(indice);
            indice--;
        }}

    private void BtnBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBorrarActionPerformed
        eliminar();
    }//GEN-LAST:event_BtnBorrarActionPerformed

    private void BtnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCancelarActionPerformed
        clearTable();
        limpiar();
    }//GEN-LAST:event_BtnCancelarActionPerformed

    private void tblCompraHierarchyChanged(java.awt.event.HierarchyEvent evt) {//GEN-FIRST:event_tblCompraHierarchyChanged
        tblCompra.getTableHeader().setReorderingAllowed(false);
        tblCompra.setRowHeight(30);
        tblCompra.setGridColor(new java.awt.Color(0, 0, 0));

        //PERSONALIZAR ENCABEZADO
        JTableHeader jtableHeader = tblCompra.getTableHeader();
        jtableHeader.setDefaultRenderer(new GestionEncabezadoTabla());
        tblCompra.setTableHeader(jtableHeader);

        tblCompra.setDefaultRenderer(Object.class, new GestionColumnas());
    }//GEN-LAST:event_tblCompraHierarchyChanged

    private void txtPVKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPVKeyTyped
        char TPresionada = evt.getKeyChar();

        if (TPresionada == KeyEvent.VK_ENTER) {
            btnADD.doClick();
        }
    }//GEN-LAST:event_txtPVKeyTyped

    private void txtCantKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCantKeyTyped
        char caracter = evt.getKeyChar();
        if (caracter < '0' || caracter > '9') {
            evt.consume();
        }

        char TPresionada = evt.getKeyChar();

        if (TPresionada == KeyEvent.VK_ENTER) {
            btnADD.doClick();
        }
    }//GEN-LAST:event_txtCantKeyTyped

    private void txtPrecioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPrecioKeyTyped
        if (!Character.isDigit(evt.getKeyChar()) && evt.getKeyChar() != '.') {
            evt.consume();
        }

        if (evt.getKeyChar() == '.' && txtPrecio.getText().contains(".")) {
            evt.consume();
        }

        char TPresionada = evt.getKeyChar();

        if (TPresionada == KeyEvent.VK_ENTER) {
            btnADD.doClick();
        }
    }//GEN-LAST:event_txtPrecioKeyTyped

    private void btnMLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMLActionPerformed
        //FiltroLibro(cmbLibro.getSelectedItem().toString());
        JfrmAgLibro1 formulario = new JfrmAgLibro1();
            formulario.jpCompr = this;
            formulario.setVisible(true);
    }//GEN-LAST:event_btnMLActionPerformed

    private void btnMLMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMLMouseReleased
        btnML.setBackground(new Color(41, 50, 65));
    }//GEN-LAST:event_btnMLMouseReleased

    private void btnMLMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMLMousePressed
        btnML.setBackground(new Color(240, 240, 240));
        btnML.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_btnMLMousePressed

    private void btnMLMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMLMouseExited
        btnML.setBackground(new Color(41, 50, 65));
        btnML.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_btnMLMouseExited

    private void btnMLMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMLMouseEntered
        btnML.setBackground(new Color(240, 240, 240));
        btnML.setForeground(new Color(0, 0, 0));
    }//GEN-LAST:event_btnMLMouseEntered

    private void txtCodigoEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigoEditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigoEditActionPerformed

    private void btnMEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMEActionPerformed
         JfrmAgEditorial formulario = new JfrmAgEditorial();
            formulario.jpComprs = this;
            formulario.setVisible(true);
    }//GEN-LAST:event_btnMEActionPerformed

    private void btnMEMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMEMouseReleased
        btnME.setBackground(new Color(41, 50, 65));
    }//GEN-LAST:event_btnMEMouseReleased

    private void btnMEMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMEMousePressed
        btnME.setBackground(new Color(240, 240, 240));
        btnME.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_btnMEMousePressed

    private void btnMEMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMEMouseExited
        btnME.setBackground(new Color(41, 50, 65));
        btnME.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_btnMEMouseExited

    private void btnMEMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMEMouseEntered
        btnME.setBackground(new Color(240, 240, 240));
        btnME.setForeground(new Color(0, 0, 0));
    }//GEN-LAST:event_btnMEMouseEntered

    private void txtclibActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtclibActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtclibActionPerformed

    private void txtclibKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtclibKeyPressed
        int keyCode = evt.getKeyCode();
        if (keyCode == KeyEvent.VK_ADD || keyCode == KeyEvent.VK_SPACE) {
            JfrmAgLibro1 formulario = new JfrmAgLibro1();
            formulario.jpCompr = this;
            formulario.setVisible(true);
        }
    }//GEN-LAST:event_txtclibKeyPressed

    private void txtEdit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEdit1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEdit1ActionPerformed

    private void txtEdit1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEdit1KeyPressed
        int keyCode = evt.getKeyCode();
        if (keyCode == KeyEvent.VK_ADD || keyCode == KeyEvent.VK_SPACE) {
            JfrmAgEditorial formulario = new JfrmAgEditorial();
            formulario.jpComprs = this;
            formulario.setVisible(true);
        }
    }//GEN-LAST:event_txtEdit1KeyPressed

    private void btnLibro1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLibro1ActionPerformed
        JfrmInfCompras formulario = new JfrmInfCompras();
            formulario.jpinf = this;
            formulario.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_btnLibro1ActionPerformed
int idlb;
int ided;
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnBorrar;
    private javax.swing.JButton BtnCancelar;
    private javax.swing.JButton btnADD;
    private javax.swing.JButton btnAgregarCompra;
    private javax.swing.JButton btnLibro1;
    private javax.swing.JButton btnME;
    private javax.swing.JButton btnML;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private com.toedter.calendar.JDateChooser jdcFecha;
    private javax.swing.JTable tblCompra;
    private javax.swing.JLabel txtCCliente;
    private javax.swing.JLabel txtCCliente1;
    private javax.swing.JLabel txtCCliente10;
    private javax.swing.JLabel txtCCliente2;
    private javax.swing.JLabel txtCCliente3;
    private javax.swing.JLabel txtCCliente4;
    private javax.swing.JLabel txtCCliente5;
    private javax.swing.JLabel txtCCliente6;
    private javax.swing.JLabel txtCCliente7;
    private javax.swing.JLabel txtCCliente9;
    private javax.swing.JTextField txtCant;
    public javax.swing.JTextField txtCodigoEdit;
    public javax.swing.JTextField txtEdit1;
    private javax.swing.JTextField txtIDCOMPRA;
    private javax.swing.JTextField txtImpuesto;
    public javax.swing.JTextField txtLibro;
    private javax.swing.JTextField txtNumeroDoc;
    private javax.swing.JTextField txtPV;
    private javax.swing.JTextField txtPrecio;
    private javax.swing.JTextField txtTotal;
    public javax.swing.JTextField txtclib;
    // End of variables declaration//GEN-END:variables
}
