/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.alejandro.library_systemnuevo;

import Beans.DatosLibross;
import Entidades.DatosLibro;
import Entidades.Enums.disponibleType;
import java.util.ArrayList;
import java.util.Iterator;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Vkaiido
 */
public class JpDatosLibro extends javax.swing.JPanel {

    /**
     * Creates new form JpBookData
     * @param main
     */
    public JpDatosLibro(JfrmMenu main) {
        initComponents();
        mainForm = main;
        carga();
        CargaCmb();
    }
    
    
       public void carga() {
        String titulos[] = {"idDatos_Libro", "idLibro", "Reseña", "Precio",
            "Cantidad", "Disponible", "Año_Publicacion"};
        //Ejemplosdearreglos
        Double numero[] = new Double[7];
        DefaultTableModel df = new DefaultTableModel(null, titulos);

        DatosLibross es = new DatosLibross();
        ArrayList<DatosLibro> listar = es.ListaDatosLibros();

        Iterator iterador = listar.iterator();
        Object fila[] = new Object[7];

        while (iterador.hasNext()) {
            //CASTEAR
            DatosLibro estBucle = (DatosLibro) iterador.next();
            fila[0] = estBucle.getIdDatos_Libro();
            fila[1] = estBucle.getIdLibro();
            fila[2] = estBucle.getReseña();
            fila[3] = estBucle.getPrecio();
            fila[4] = estBucle.getCantidad();
            fila[5] = estBucle.getDisponible().name();
            fila[6] = estBucle.getAño_Publicacion();
            df.addRow(fila);
        }
        TblDatosLibro.setModel(df);
    }

       
       void CargaCmb() {
        for (var Disponible : disponibleType.values()) {
            cmbDisp.addItem(Disponible.toString());
        }
    }
       
       
       void Limpiar(){
    txtIdDatos.setText("");
    txtIdLibro1.setText("");
    txtPrecio.setText("");
    txtCantidad.setText("");
    cmbDisp.setSelectedIndex(0);
    txtAñoPublicacion.setText("");
    txtReseña.setText("");

}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnRegresar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        txtIdDatos = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        txtIdLibro1 = new javax.swing.JTextField();
        txtAñoPublicacion = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        BtnDL = new javax.swing.JButton();
        txtPrecio = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        txtCantidad = new javax.swing.JTextField();
        txtReseña = new javax.swing.JTextField();
        cmbDisp = new javax.swing.JComboBox<>();
        btnUDL = new javax.swing.JButton();
        BtnEDL = new javax.swing.JButton();
        lblBarrer = new javax.swing.JLabel();
        jScrollPane11 = new javax.swing.JScrollPane();
        TblDatosLibro = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));

        btnRegresar.setBackground(new java.awt.Color(61, 90, 128));
        btnRegresar.setForeground(new java.awt.Color(255, 255, 255));
        btnRegresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/back.png"))); // NOI18N
        btnRegresar.setText("Regresar");
        btnRegresar.setContentAreaFilled(false);
        btnRegresar.setOpaque(true);
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });

        jPanel1.setBackground(java.awt.SystemColor.controlHighlight);

        jLabel19.setText("Disponible");

        txtIdDatos.setEnabled(false);

        jLabel20.setText("Año de Publicacion");

        txtIdLibro1.setEnabled(false);

        jLabel14.setText("Reseña");

        jLabel12.setText("Id Datos");

        jLabel13.setText("Id Libro");

        jLabel15.setText("Precio");

        BtnDL.setBackground(new java.awt.Color(0, 153, 51));
        BtnDL.setForeground(new java.awt.Color(255, 255, 255));
        BtnDL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/floppy-disk.png"))); // NOI18N
        BtnDL.setText("Registrar");
        BtnDL.setContentAreaFilled(false);
        BtnDL.setOpaque(true);
        BtnDL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnDLActionPerformed(evt);
            }
        });

        jLabel18.setText("Cantidad");

        btnUDL.setBackground(new java.awt.Color(238, 108, 77));
        btnUDL.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnUDL.setForeground(new java.awt.Color(255, 255, 255));
        btnUDL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Update.png"))); // NOI18N
        btnUDL.setText("Actualizar");
        btnUDL.setContentAreaFilled(false);
        btnUDL.setOpaque(true);
        btnUDL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUDLActionPerformed(evt);
            }
        });

        BtnEDL.setBackground(new java.awt.Color(255, 51, 51));
        BtnEDL.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BtnEDL.setForeground(new java.awt.Color(255, 255, 255));
        BtnEDL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/trash.png"))); // NOI18N
        BtnEDL.setText("Eliminar");
        BtnEDL.setContentAreaFilled(false);
        BtnEDL.setOpaque(true);
        BtnEDL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnEDLActionPerformed(evt);
            }
        });

        lblBarrer.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblBarrer.setForeground(new java.awt.Color(255, 0, 0));
        lblBarrer.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBarrer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/broom.png"))); // NOI18N
        lblBarrer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblBarrerMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel20)
                                .addGap(22, 22, 22)
                                .addComponent(txtAñoPublicacion))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel19)
                                    .addComponent(jLabel18)
                                    .addComponent(jLabel15))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cmbDisp, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel14))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtReseña, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 59, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtIdLibro1, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                            .addComponent(txtIdDatos))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblBarrer, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BtnDL, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnUDL, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BtnEDL, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel12)
                        .addComponent(txtIdDatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblBarrer, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtIdLibro1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(cmbDisp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAñoPublicacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20))
                .addGap(18, 18, 18)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtReseña, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnDL, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUDL, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnEDL, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(80, Short.MAX_VALUE))
        );

        TblDatosLibro.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        TblDatosLibro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TblDatosLibroMouseClicked(evt);
            }
        });
        TblDatosLibro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TblDatosLibroKeyReleased(evt);
            }
        });
        jScrollPane11.setViewportView(TblDatosLibro);
        TblDatosLibro.getAccessibleContext().setAccessibleName("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnRegresar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE))
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(btnRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, 417, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, 0))
        );
    }// </editor-fold>//GEN-END:initComponents

    JfrmMenu mainForm;
    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        mainForm.currentPanel = null;
        mainForm.showJPanel(new JpLibro(mainForm));
        
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void TblDatosLibroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TblDatosLibroMouseClicked

    }//GEN-LAST:event_TblDatosLibroMouseClicked

    private void TblDatosLibroKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TblDatosLibroKeyReleased
        //        if ((evt.getKeyCode() == KeyEvent.VK_DOWN) || (evt.getKeyCode() == KeyEvent.VK_UP)) {
            //
            //            isSelect = true;
            //            try {
                //                int filaSeleccionada = this.TblDatosEscritor.getSelectedRow();
                //                this.txtIdEscritor.setText(TblDatosEscritor.getValueAt(filaSeleccionada, 0).toString());
                //                this.txtId.setText(TblDatosEscritor.getValueAt(filaSeleccionada, 1).toString());
                //                this.txtFechaNacimiento.setText(TblDatosEscritor.getValueAt(filaSeleccionada, 2).toString());
                //                this.txtLugarNacimiento.setText(TblDatosEscritor.getValueAt(filaSeleccionada, 3).toString());
                //                this.txtFechaDeceso.setText(TblDatosEscritor.getValueAt(filaSeleccionada, 4).toString());
                //                this.txtLugarDeceso.setText(TblDatosEscritor.getValueAt(filaSeleccionada, 5).toString());
                //                this.jTextArea2.setText(TblDatosEscritor.getValueAt(filaSeleccionada, 6).toString());
                //            } catch (Exception e) {
                //                JOptionPane.showMessageDialog(null, "Error al leer la tabla", "Error", JOptionPane.WARNING_MESSAGE);
                //            }
            //
            //        }
    }//GEN-LAST:event_TblDatosLibroKeyReleased

    private void BtnDLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnDLActionPerformed
            
            DatosLibro dl = new DatosLibro();
            DatosLibross dLDAO = new DatosLibross();

            dl.setIdLibro(Integer.parseInt(txtIdLibro1.getText()));
            dl.setPrecio(Double.parseDouble(txtPrecio.getText()));
            dl.setCantidad(Integer.parseInt(txtCantidad.getText()));
            dl.setDisponible(disponibleType.values()[cmbDisp.getSelectedIndex()]);
            dl.setReseña(txtReseña.getText());
            dl.setAño_Publicacion(txtAñoPublicacion.getText());

            dLDAO.AddDatosLibros(dl);
            carga();
            Limpiar();

    }//GEN-LAST:event_BtnDLActionPerformed

    private void btnUDLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUDLActionPerformed


            if (TblDatosLibro.getSelectedRowCount()>0) {
            DatosLibro dl = new DatosLibro();
            DatosLibross dLDAO = new DatosLibross();

            dl.setIdDatos_Libro(Integer.parseInt(txtIdDatos.getText()));
            dl.setIdLibro(Integer.parseInt(txtIdLibro1.getText()));
            dl.setPrecio(Double.parseDouble(txtPrecio.getText()));
            dl.setCantidad(Integer.parseInt(txtCantidad.getText()));
            dl.setDisponible(disponibleType.values()[cmbDisp.getSelectedIndex()]);
            dl.setReseña(txtReseña.getText());
            dl.setAño_Publicacion(txtAñoPublicacion.getText());

            dLDAO.UpdateDL(dl);
            carga();
            Limpiar();

            //isSelect = false;
        

        } else {
            JOptionPane.showMessageDialog(null, "Seleccione una fila", "Aviso", 1);
        }
        
        
    }//GEN-LAST:event_btnUDLActionPerformed

    private void BtnEDLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEDLActionPerformed
        if (TblDatosLibro.getSelectedRowCount()>0) 
        {
            DatosLibro dl = new DatosLibro();
            DatosLibross dLDAO = new DatosLibross();

            dl.setIdDatos_Libro(Integer.parseInt(txtIdDatos.getText()));
            dl.setIdLibro(Integer.parseInt(txtIdLibro1.getText()));
            dl.setPrecio(Double.parseDouble(txtPrecio.getText()));
            dl.setCantidad(Integer.parseInt(txtCantidad.getText()));
            dl.setDisponible(disponibleType.values()[cmbDisp.getSelectedIndex()]);
            dl.setReseña(txtReseña.getText());
            dl.setAño_Publicacion(txtAñoPublicacion.getText());

            dLDAO.DeleteDL(dl);
            carga();
            Limpiar();

            //isSelect = false;
        

        } else {
            JOptionPane.showMessageDialog(null, "Seleccione una fila", "Aviso", 1);
        }
        
    }//GEN-LAST:event_BtnEDLActionPerformed

    private void lblBarrerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBarrerMouseClicked
        Limpiar();
    }//GEN-LAST:event_lblBarrerMouseClicked

  public boolean isSelect = false;
  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnDL;
    private javax.swing.JButton BtnEDL;
    private javax.swing.JTable TblDatosLibro;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JButton btnUDL;
    public javax.swing.JComboBox<String> cmbDisp;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JLabel lblBarrer;
    public javax.swing.JTextField txtAñoPublicacion;
    public javax.swing.JTextField txtCantidad;
    public javax.swing.JTextField txtIdDatos;
    public javax.swing.JTextField txtIdLibro1;
    public javax.swing.JTextField txtPrecio;
    private javax.swing.JTextField txtReseña;
    // End of variables declaration//GEN-END:variables
}
