/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.alejandro.library_systemnuevo;

import Beans.DatosEscritores;
import Beans.Editorials;
import Entidades.DatosEscritor;
import Entidades.Editorial;
import Entidades.Escritor;
import java.awt.Color;
import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import utilidades.GestionColumnas;
import utilidades.GestionEncabezadoTabla;

/**
 *
 * @author Vkaiido
 */
public class JpDatosEscritor extends javax.swing.JPanel {

    /**
     * Creates new form JpWritterD
     */
    public JpDatosEscritor(JfrmMenu main) {
        initComponents();
        mainForm = main;
        carga();
    }

    public void limpiar() {
        txtIdEscritor2.setText("");
        txtId.setText("");
        //txtFechaNacimiento.setText("");
        txtLugarNacimiento.setText("");
        //txtFechaDeceso.setText("");
        txtLugarDeceso.setText("");
        txtBiografia.setText("");

    }

    public void carga() {
        String titulos[] = {"idDatos_Escritor", "idEscritor", "Fecha_Nacimiento", "Lugar_Nacimiento",
            "Fecha_Deceso", "Lugar_Deceso", "Biografia"};
        //Ejemplosdearreglos
        Double numero[] = new Double[8];
        DefaultTableModel df = new DefaultTableModel(null, titulos);

        DatosEscritores es = new DatosEscritores();
        ArrayList<DatosEscritor> listar = es.ListaDatosEscritor();

        Iterator iterador = listar.iterator();
        Object fila[] = new Object[8];

        while (iterador.hasNext()) {
            //CASTEAR
            DatosEscritor estBucle = (DatosEscritor) iterador.next();
            fila[0] = estBucle.getIdDatos_Escritor();
            fila[1] = estBucle.getIdEscritor();
            fila[2] = estBucle.getFecha_Nacimiento();
            fila[3] = estBucle.getLugar_Nacimiento();
            fila[4] = estBucle.getFecha_Deceso();
            fila[5] = estBucle.getLugar_Deceso();
            fila[6] = estBucle.getBiografia();
            df.addRow(fila);
        }
        TblDatosEscritor.setModel(df);

        TblDatosEscritor.getTableHeader().setReorderingAllowed(false);
        TblDatosEscritor.setRowHeight(30);
        TblDatosEscritor.setGridColor(new java.awt.Color(0, 0, 0));

        //PERSONALIZAR ENCABEZADO
        JTableHeader jtableHeader = TblDatosEscritor.getTableHeader();
        jtableHeader.setDefaultRenderer(new GestionEncabezadoTabla());
        TblDatosEscritor.setTableHeader(jtableHeader);

        TblDatosEscritor.setDefaultRenderer(Object.class, new GestionColumnas());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane11 = new javax.swing.JScrollPane();
        TblDatosEscritor = new javax.swing.JTable();
        btnRegresar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        txtId = new javax.swing.JTextField();
        jLabel70 = new javax.swing.JLabel();
        jLabel74 = new javax.swing.JLabel();
        jLabel72 = new javax.swing.JLabel();
        jLabel69 = new javax.swing.JLabel();
        txtLugarNacimiento = new javax.swing.JTextField();
        txtLugarDeceso = new javax.swing.JTextField();
        txtIdEscritor2 = new javax.swing.JTextField();
        jLabel71 = new javax.swing.JLabel();
        btnIngresar = new javax.swing.JButton();
        jLabel68 = new javax.swing.JLabel();
        jLabel73 = new javax.swing.JLabel();
        txtBiografia = new javax.swing.JTextField();
        btnUDL = new javax.swing.JButton();
        BtnEDL = new javax.swing.JButton();
        JDCFN = new com.toedter.calendar.JDateChooser();
        JDCFD = new com.toedter.calendar.JDateChooser();

        setBackground(new java.awt.Color(255, 255, 255));

        TblDatosEscritor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        TblDatosEscritor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TblDatosEscritorMouseClicked(evt);
            }
        });
        TblDatosEscritor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TblDatosEscritorKeyReleased(evt);
            }
        });
        jScrollPane11.setViewportView(TblDatosEscritor);

        btnRegresar.setBackground(new java.awt.Color(61, 90, 128));
        btnRegresar.setForeground(new java.awt.Color(255, 255, 255));
        btnRegresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/back.png"))); // NOI18N
        btnRegresar.setText("Regresar");
        btnRegresar.setContentAreaFilled(false);
        btnRegresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegresar.setOpaque(true);
        btnRegresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnRegresarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnRegresarMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnRegresarMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnRegresarMouseReleased(evt);
            }
        });
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });

        jPanel1.setBackground(java.awt.SystemColor.controlHighlight);

        jLabel70.setText("Fecha de Deceso");

        jLabel74.setText("Lugar de Nacimiento");

        jLabel72.setText("ID");

        jLabel69.setText("ID_Escritor");

        txtIdEscritor2.setEnabled(false);

        jLabel71.setText("Fecha de Nacimiento");

        btnIngresar.setBackground(new java.awt.Color(0, 153, 51));
        btnIngresar.setForeground(new java.awt.Color(255, 255, 255));
        btnIngresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/floppy-disk.png"))); // NOI18N
        btnIngresar.setText("Ingresar");
        btnIngresar.setContentAreaFilled(false);
        btnIngresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnIngresar.setOpaque(true);
        btnIngresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnIngresarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnIngresarMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnIngresarMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnIngresarMouseReleased(evt);
            }
        });
        btnIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarActionPerformed(evt);
            }
        });

        jLabel68.setText("Lugar de Deceso");

        jLabel73.setText("Biografia");

        btnUDL.setBackground(new java.awt.Color(238, 108, 77));
        btnUDL.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnUDL.setForeground(new java.awt.Color(255, 255, 255));
        btnUDL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Update.png"))); // NOI18N
        btnUDL.setText("Actualizar");
        btnUDL.setContentAreaFilled(false);
        btnUDL.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnUDL.setOpaque(true);
        btnUDL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnUDLMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnUDLMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnUDLMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnUDLMouseReleased(evt);
            }
        });
        btnUDL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUDLActionPerformed(evt);
            }
        });

        BtnEDL.setBackground(new java.awt.Color(255, 51, 51));
        BtnEDL.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BtnEDL.setForeground(new java.awt.Color(255, 255, 255));
        BtnEDL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/trash.png"))); // NOI18N
        BtnEDL.setText("Eliminar");
        BtnEDL.setContentAreaFilled(false);
        BtnEDL.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnEDL.setOpaque(true);
        BtnEDL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BtnEDLMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BtnEDLMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BtnEDLMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                BtnEDLMouseReleased(evt);
            }
        });
        BtnEDL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnEDLActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel71)
                                        .addComponent(jLabel74)
                                        .addComponent(jLabel70)
                                        .addComponent(jLabel68)
                                        .addComponent(jLabel73))
                                    .addGap(18, 18, 18)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(JDCFD, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
                                        .addComponent(JDCFN, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtLugarNacimiento, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtLugarDeceso)
                                        .addComponent(txtBiografia)))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(txtIdEscritor2, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 101, Short.MAX_VALUE)
                                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnIngresar, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnUDL)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BtnEDL, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE)))
                        .addContainerGap(24, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel72)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel69)
                        .addGap(111, 111, 111))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel72)
                    .addComponent(jLabel69))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtIdEscritor2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel71)
                    .addComponent(JDCFN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtLugarNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel74))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel70)
                    .addComponent(JDCFD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel68)
                    .addComponent(txtLugarDeceso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel73)
                    .addComponent(txtBiografia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 153, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnIngresar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUDL, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnEDL, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane11, javax.swing.GroupLayout.DEFAULT_SIZE, 527, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(btnRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addGap(33, 33, 33))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarActionPerformed
        if (txtId.getText().equals("") || txtLugarNacimiento.getText().equals("") || JDCFN.getDate() == null
                || txtLugarNacimiento.getText().equals("") || JDCFD.getDate() == null || txtLugarDeceso.getText().equals("") || txtBiografia.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Llenar campos vacios");

        } else {
            DatosEscritor es = new DatosEscritor();
            DatosEscritores esDAO = new DatosEscritores();

            es.setIdEscritor(Integer.parseInt(txtId.getText()));
            es.setFecha_Nacimiento(JDCFN.getDate());
            es.setLugar_Nacimiento(txtLugarNacimiento.getText());
            es.setFecha_Deceso(JDCFD.getDate());
            es.setLugar_Deceso(txtLugarDeceso.getText());
            es.setBiografia(txtBiografia.getText());

            esDAO.AddDatosEscritor(es);
            txtId.requestFocus();
            carga();
            limpiar();
        }

    }//GEN-LAST:event_btnIngresarActionPerformed

    private void TblDatosEscritorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TblDatosEscritorMouseClicked
        int selectedRow = TblDatosEscritor.getSelectedRow();
        isSelect = true;

        try {
            txtIdEscritor2.setText(String.valueOf(TblDatosEscritor.getValueAt(selectedRow, 0)));
            txtId.setText(String.valueOf(TblDatosEscritor.getValueAt(selectedRow, 1)));
            JDCFN.setDate((Date) TblDatosEscritor.getValueAt(selectedRow, 2));
            txtLugarNacimiento.setText(String.valueOf(TblDatosEscritor.getValueAt(selectedRow, 3)));
            JDCFD.setDate((Date) TblDatosEscritor.getValueAt(selectedRow, 4));
            txtLugarDeceso.setText(String.valueOf(TblDatosEscritor.getValueAt(selectedRow, 5)));
            txtBiografia.setText(String.valueOf(TblDatosEscritor.getValueAt(selectedRow, 6)));

        } catch (Exception ex) {
        }
    }//GEN-LAST:event_TblDatosEscritorMouseClicked

    private void TblDatosEscritorKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TblDatosEscritorKeyReleased
        //        if ((evt.getKeyCode() == KeyEvent.VK_DOWN) || (evt.getKeyCode() == KeyEvent.VK_UP)) {
        //
        //            isSelect = true;
        //            try {
        //                int filaSeleccionada = this.TblDatosEscritor.getSelectedRow();
        //                this.txtIdEscritor.setText(TblDatosEscritor.getValueAt(filaSeleccionada, 0).toString());
        //                this.txtId.setText(TblDatosEscritor.getValueAt(filaSeleccionada, 1).toString());
        //                this.txtFechaNacimiento.setText(TblDatosEscritor.getValueAt(filaSeleccionada, 2).toString());
        //                this.txtLugarNacimiento.setText(TblDatosEscritor.getValueAt(filaSeleccionada, 3).toString());
        //                this.txtFechaDeceso.setText(TblDatosEscritor.getValueAt(filaSeleccionada, 4).toString());
        //                this.txtLugarDeceso.setText(TblDatosEscritor.getValueAt(filaSeleccionada, 5).toString());
        //                this.jTextArea2.setText(TblDatosEscritor.getValueAt(filaSeleccionada, 6).toString());
        //            } catch (Exception e) {
        //                JOptionPane.showMessageDialog(null, "Error al leer la tabla", "Error", JOptionPane.WARNING_MESSAGE);
        //            }
        //
        //        }
    }//GEN-LAST:event_TblDatosEscritorKeyReleased

    public JfrmMenu mainForm;
    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        mainForm.currentPanel = null;
        mainForm.showJPanel(new JpEscritor(mainForm));

    }//GEN-LAST:event_btnRegresarActionPerformed

    private void btnUDLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUDLActionPerformed

        if (TblDatosEscritor.getSelectedRowCount() > 0) {

            DatosEscritor es = new DatosEscritor();
            DatosEscritores esDAO = new DatosEscritores();

            es.setIdDatos_Escritor(Integer.parseInt(txtIdEscritor2.getText()));
            es.setIdEscritor(Integer.parseInt(txtId.getText()));
            es.setFecha_Nacimiento(JDCFN.getDate());
            es.setLugar_Nacimiento(txtLugarNacimiento.getText());
            es.setFecha_Deceso(JDCFD.getDate());
            es.setLugar_Deceso(txtLugarDeceso.getText());
            es.setBiografia(txtBiografia.getText());

            esDAO.UpdateDatosEscritor(es);
            txtId.requestFocus();
            carga();
            limpiar();

            //isSelect = false;
        } else {
            JOptionPane.showMessageDialog(null, "Seleccione una fila", "Aviso", 1);
        }

    }//GEN-LAST:event_btnUDLActionPerformed

    private void BtnEDLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEDLActionPerformed
        if (TblDatosEscritor.getSelectedRowCount() > 0) {
            DatosEscritor es = new DatosEscritor();
            DatosEscritores esDAO = new DatosEscritores();
            es.setIdDatos_Escritor(Integer.parseInt(txtIdEscritor2.getText()));
            es.setIdEscritor(Integer.parseInt(txtId.getText()));
            es.setFecha_Nacimiento(JDCFN.getDate());
            es.setLugar_Nacimiento(txtLugarNacimiento.getText());
            es.setFecha_Deceso(JDCFD.getDate());
            es.setLugar_Deceso(txtLugarDeceso.getText());
            es.setBiografia(txtBiografia.getText());

            esDAO.DeleteDE(es);
            txtId.requestFocus();
            carga();
            limpiar();

            //isSelect = false;
        } else {
            JOptionPane.showMessageDialog(null, "Seleccione una fila", "Aviso", 1);
        }

    }//GEN-LAST:event_BtnEDLActionPerformed

    private void btnIngresarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnIngresarMouseEntered
        btnIngresar.setBackground(new Color(75, 163, 252));
    }//GEN-LAST:event_btnIngresarMouseEntered

    private void btnIngresarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnIngresarMouseExited
        btnIngresar.setBackground(new Color(0,153,51));
    }//GEN-LAST:event_btnIngresarMouseExited

    private void btnIngresarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnIngresarMousePressed
        btnIngresar.setBackground(new Color(75, 163, 252));
    }//GEN-LAST:event_btnIngresarMousePressed

    private void btnIngresarMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnIngresarMouseReleased
        btnIngresar.setBackground(new Color(0,153,51));
    }//GEN-LAST:event_btnIngresarMouseReleased

    private void btnUDLMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUDLMouseEntered
        btnUDL.setBackground(new Color(75, 163, 252));
    }//GEN-LAST:event_btnUDLMouseEntered

    private void btnUDLMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUDLMouseExited
        btnUDL.setBackground(new Color(238,108,77));
    }//GEN-LAST:event_btnUDLMouseExited

    private void btnUDLMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUDLMousePressed
        btnUDL.setBackground(new Color(75, 163, 252));
    }//GEN-LAST:event_btnUDLMousePressed

    private void btnUDLMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUDLMouseReleased
         btnUDL.setBackground(new Color(238,108,77));
    }//GEN-LAST:event_btnUDLMouseReleased

    private void BtnEDLMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnEDLMouseEntered
        BtnEDL.setBackground(new Color(75, 163, 252));
    }//GEN-LAST:event_BtnEDLMouseEntered

    private void BtnEDLMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnEDLMouseExited
         BtnEDL.setBackground(new Color(255,51,51));
    }//GEN-LAST:event_BtnEDLMouseExited

    private void BtnEDLMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnEDLMousePressed
        BtnEDL.setBackground(new Color(75, 163, 252));
    }//GEN-LAST:event_BtnEDLMousePressed

    private void BtnEDLMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnEDLMouseReleased
        BtnEDL.setBackground(new Color(255,51,51));
    }//GEN-LAST:event_BtnEDLMouseReleased

    private void btnRegresarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegresarMouseEntered
         btnRegresar.setBackground(new Color(75, 163, 252));
    }//GEN-LAST:event_btnRegresarMouseEntered

    private void btnRegresarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegresarMouseExited
        btnRegresar.setBackground(new Color(61,90,128));
    }//GEN-LAST:event_btnRegresarMouseExited

    private void btnRegresarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegresarMousePressed
        btnRegresar.setBackground(new Color(41, 50, 65));
    }//GEN-LAST:event_btnRegresarMousePressed

    private void btnRegresarMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegresarMouseReleased
        btnRegresar.setBackground(new Color(61,90,128));
    }//GEN-LAST:event_btnRegresarMouseReleased

    public boolean isSelect = false;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnEDL;
    private com.toedter.calendar.JDateChooser JDCFD;
    private com.toedter.calendar.JDateChooser JDCFN;
    private javax.swing.JTable TblDatosEscritor;
    private javax.swing.JButton btnIngresar;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JButton btnUDL;
    private javax.swing.JLabel jLabel68;
    private javax.swing.JLabel jLabel69;
    private javax.swing.JLabel jLabel70;
    private javax.swing.JLabel jLabel71;
    private javax.swing.JLabel jLabel72;
    private javax.swing.JLabel jLabel73;
    private javax.swing.JLabel jLabel74;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JTextField txtBiografia;
    public static javax.swing.JTextField txtId;
    private javax.swing.JTextField txtIdEscritor2;
    private javax.swing.JTextField txtLugarDeceso;
    private javax.swing.JTextField txtLugarNacimiento;
    // End of variables declaration//GEN-END:variables
}
