/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.alejandro.library_systemnuevo;

import Beans.Editorials;
import Entidades.Editorial;
import java.util.ArrayList;
import java.util.Iterator;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Vkaiido
 */
public class JpEditorial extends javax.swing.JPanel {

    /**
     * Creates new form JpEditorial
     */
    public JpEditorial() {
        initComponents();
        carga();
    }
    
    public void carga() {
        String titulos[] = {"Id", "Codigo", "Nombre", "Direccion", "Telefono"};
        //Ejemplosdearreglos
        Double numero[] = new Double[5];
        DefaultTableModel df = new DefaultTableModel(null, titulos);

        Editorials es = new Editorials();
        ArrayList<Editorial> listar = es.ListaEditorial();

        Iterator iterador = listar.iterator();
        Object fila[] = new Object[5];

        while (iterador.hasNext()) {
            //CASTEAR
            Editorial estBucle = (Editorial) iterador.next();
            fila[0] = estBucle.getIdEditorial();
            fila[1] = estBucle.getCodigoEditorial();
            fila[2] = estBucle.getNombre_Editorial();
            fila[3] = estBucle.getDireccion_Editorial();
            fila[4] = estBucle.getTelefono_Editorial();
            df.addRow(fila);
        }
        TblEditorial.setModel(df);
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        TblEditorial = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        btnNuevaEditorial = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        btmBorrar = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        TblEditorial.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        TblEditorial.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        TblEditorial.setGridColor(new java.awt.Color(0, 0, 0));
        TblEditorial.setSelectionBackground(new java.awt.Color(161, 220, 173));
        jScrollPane1.setViewportView(TblEditorial);

        jLabel1.setText("GESTIÓN DE EDITORIALES");

        btnNuevaEditorial.setText("Nuevo");
        btnNuevaEditorial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevaEditorialActionPerformed(evt);
            }
        });

        btnActualizar.setBackground(java.awt.Color.blue);
        btnActualizar.setFont(new java.awt.Font("Roboto Bk", 0, 14)); // NOI18N
        btnActualizar.setForeground(new java.awt.Color(254, 254, 255));
        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        btmBorrar.setBackground(java.awt.Color.blue);
        btmBorrar.setFont(new java.awt.Font("Roboto Bk", 0, 14)); // NOI18N
        btmBorrar.setForeground(new java.awt.Color(254, 254, 255));
        btmBorrar.setText("Eliminar");
        btmBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btmBorrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btmBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnNuevaEditorial, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1008, Short.MAX_VALUE))))
                .addGap(24, 24, 24))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel1))
                    .addComponent(btnNuevaEditorial, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btmBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnNuevaEditorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevaEditorialActionPerformed
        JfrmEditorialCrud frm = new JfrmEditorialCrud();
        frm.jp = this;
        frm.setVisible(true);
    }//GEN-LAST:event_btnNuevaEditorialActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        if (TblEditorial.getSelectedRowCount() > 0) {

            JfrmEditorialCrud frm = new JfrmEditorialCrud();
            int selectedRow = TblEditorial.getSelectedRow();
            frm.txtIdEditorial1.setText(String.valueOf(TblEditorial.getValueAt(selectedRow, 0)));
            frm.txtCodigoEditorial.setText(String.valueOf(TblEditorial.getValueAt(selectedRow, 1)));
            frm.txtNombreEditorial.setText(String.valueOf(TblEditorial.getValueAt(selectedRow, 2)));
            frm.txtDireccionEditorial.setText(String.valueOf(TblEditorial.getValueAt(selectedRow, 3)));
            frm.txtTelefonoEditorial.setText(String.valueOf(TblEditorial.getValueAt(selectedRow, 4)));
            
            frm.jp = this;
            frm.setVisible(true);

            //isSelect = false;
        } else {
            JOptionPane.showMessageDialog(null, "Seleccione una fila", "Aviso", 1);
        }
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void btmBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btmBorrarActionPerformed
        if (TblEditorial.getSelectedRowCount()>0) {
             Editorial es = new Editorial();
            Editorials esDAO = new Editorials();
            int selectedRow =TblEditorial.getSelectedRow();
            es.setIdEditorial(Integer.parseInt(TblEditorial.getValueAt(selectedRow, 0).toString()));

             esDAO.DeleteEditorial(es);
             carga();
                //isSelect = false;
            } else {
                JOptionPane.showMessageDialog(null, "Seleccione una fila", "Aviso", 1);
            }
    }//GEN-LAST:event_btmBorrarActionPerformed
//public boolean isSelect = false;


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TblEditorial;
    private javax.swing.JButton btmBorrar;
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnNuevaEditorial;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
