/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.alejandro.library_systemnuevo;

import DAO.EscritoresDAO;
import javax.swing.*;
import Entidades.Escritor;
import java.awt.Color;
import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import utilidades.GestionColumnas;
import utilidades.GestionEncabezadoTabla;

/**
 *
 * @author wilian
 */
public class JpEscritor extends javax.swing.JPanel {

    /**
     * Creates new form JpWriter
     */
    public JpEscritor(JfrmMenu main) {
        initComponents();
        carga();
        mainForm = main;
    }

    public void carga() {
        String titulos[] = {"Id", "Codigo", "Nombre", "Apellido", "Pais","Fecha_Nacimiento","Biografia"};
        
//        Double numero[] = new Double[8];
        DefaultTableModel df = new DefaultTableModel(null, titulos);

        EscritoresDAO es = new EscritoresDAO();
        ArrayList<Escritor> listar = es.ListaEscritor();

        Iterator iterador = listar.iterator();
        Object fila[] = new Object[8];

        while (iterador.hasNext()) {
            //CASTEAR
            Escritor estBucle = (Escritor) iterador.next();
            fila[0] = estBucle.getIdEscritor();
            fila[1] = estBucle.getCodigo_Escritor();
            fila[2] = estBucle.getNombre_Escritor();
            fila[3] = estBucle.getApellido_Escritor();
            fila[4] = estBucle.getPais_Escritor();
            fila[5] = estBucle.getFecha_Nacimiento();
            fila[6] = estBucle.getBiografia();
            df.addRow(fila);
        }
        TblEscritor.setModel(df);

        //DISEÑO TABLA
        TblEscritor.getTableHeader().setReorderingAllowed(false);
        TblEscritor.setRowHeight(30);
        TblEscritor.setGridColor(new java.awt.Color(0, 0, 0));

        //PERSONALIZAR ENCABEZADO
        JTableHeader jtableHeader = TblEscritor.getTableHeader();
        jtableHeader.setDefaultRenderer(new GestionEncabezadoTabla());
        TblEscritor.setTableHeader(jtableHeader);

        TblEscritor.setDefaultRenderer(Object.class, new GestionColumnas());
    }

    public void cargaBusq() {
        String titulos[] = {"Id", "Codigo", "Nombre", "Apellido", "Pais","Fecha_Nacimiento","Biografia"};

//        Double numero[] = new Double[8];
        DefaultTableModel df = new DefaultTableModel(null, titulos);

        EscritoresDAO es = new EscritoresDAO();
        ArrayList<Escritor> listar = es.BusquedaEscritor(txtBusqEs.getText());

        Iterator iterador = listar.iterator();
        Object fila[] = new Object[8];

        while (iterador.hasNext()) {
            //CASTEAR
            Escritor estBucle = (Escritor) iterador.next();
            fila[0] = estBucle.getIdEscritor();
            fila[1] = estBucle.getCodigo_Escritor();
            fila[2] = estBucle.getNombre_Escritor();
            fila[3] = estBucle.getApellido_Escritor();
            fila[4] = estBucle.getPais_Escritor();
            fila[5] = estBucle.getFecha_Nacimiento();
            fila[6] = estBucle.getBiografia();

            df.addRow(fila);
        }
        TblEscritor.setModel(df);

        //DISEÑO TABLA
        TblEscritor.getTableHeader().setReorderingAllowed(false);
        TblEscritor.setRowHeight(30);
        TblEscritor.setGridColor(new java.awt.Color(0, 0, 0));

        //PERSONALIZAR ENCABEZADO
        JTableHeader jtableHeader = TblEscritor.getTableHeader();
        jtableHeader.setDefaultRenderer(new GestionEncabezadoTabla());
        TblEscritor.setTableHeader(jtableHeader);

        TblEscritor.setDefaultRenderer(Object.class, new GestionColumnas());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnNuevoEscritor = new javax.swing.JButton();
        jScrollPane9 = new javax.swing.JScrollPane();
        TblEscritor = new javax.swing.JTable();
        btnUpdate = new javax.swing.JButton();
        btnEliminar1 = new javax.swing.JButton();
        txtBusqEs = new javax.swing.JTextField();
        btnBusqueda = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1050, 540));

        jLabel1.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(41, 50, 65));
        jLabel1.setText("GESTIÓN DE ESCRITORES");

        btnNuevoEscritor.setBackground(new java.awt.Color(0, 153, 51));
        btnNuevoEscritor.setForeground(new java.awt.Color(255, 255, 255));
        btnNuevoEscritor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/new-file.png"))); // NOI18N
        btnNuevoEscritor.setText("Nuevo");
        btnNuevoEscritor.setContentAreaFilled(false);
        btnNuevoEscritor.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnNuevoEscritor.setOpaque(true);
        btnNuevoEscritor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnNuevoEscritorMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnNuevoEscritorMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnNuevoEscritorMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnNuevoEscritorMouseReleased(evt);
            }
        });
        btnNuevoEscritor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoEscritorActionPerformed(evt);
            }
        });

        TblEscritor.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        TblEscritor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        TblEscritor.setGridColor(new java.awt.Color(0, 0, 0));
        TblEscritor.setSelectionBackground(new java.awt.Color(161, 220, 173));
        TblEscritor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TblEscritorMouseClicked(evt);
            }
        });
        TblEscritor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TblEscritorKeyReleased(evt);
            }
        });
        jScrollPane9.setViewportView(TblEscritor);

        btnUpdate.setBackground(new java.awt.Color(238, 108, 77));
        btnUpdate.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnUpdate.setForeground(new java.awt.Color(255, 255, 255));
        btnUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Update.png"))); // NOI18N
        btnUpdate.setText("Actualizar");
        btnUpdate.setContentAreaFilled(false);
        btnUpdate.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnUpdate.setOpaque(true);
        btnUpdate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnUpdateMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnUpdateMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnUpdateMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnUpdateMouseReleased(evt);
            }
        });
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnEliminar1.setBackground(new java.awt.Color(255, 51, 51));
        btnEliminar1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnEliminar1.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/trash (1).png"))); // NOI18N
        btnEliminar1.setText("Eliminar");
        btnEliminar1.setContentAreaFilled(false);
        btnEliminar1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEliminar1.setOpaque(true);
        btnEliminar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnEliminar1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnEliminar1MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnEliminar1MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnEliminar1MouseReleased(evt);
            }
        });
        btnEliminar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminar1ActionPerformed(evt);
            }
        });

        txtBusqEs.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtBusqEsKeyPressed(evt);
            }
        });

        btnBusqueda.setBackground(new java.awt.Color(41, 50, 65));
        btnBusqueda.setForeground(new java.awt.Color(255, 255, 255));
        btnBusqueda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/search.png"))); // NOI18N
        btnBusqueda.setText("Buscar");
        btnBusqueda.setContentAreaFilled(false);
        btnBusqueda.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBusqueda.setOpaque(true);
        btnBusqueda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnBusquedaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnBusquedaMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnBusquedaMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnBusquedaMouseReleased(evt);
            }
        });
        btnBusqueda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBusquedaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(170, 170, 170)
                        .addComponent(txtBusqEs, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(btnBusqueda)
                        .addGap(52, 52, 52)
                        .addComponent(btnNuevoEscritor, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane9)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnEliminar1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNuevoEscritor, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtBusqEs, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addComponent(jScrollPane9, javax.swing.GroupLayout.DEFAULT_SIZE, 367, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEliminar1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnNuevoEscritorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoEscritorActionPerformed
        JfrmEscritorCrud frm = new JfrmEscritorCrud();
        frm.jpE = this;
        frm.setVisible(true);
    }//GEN-LAST:event_btnNuevoEscritorActionPerformed

    private void TblEscritorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TblEscritorMouseClicked

    }//GEN-LAST:event_TblEscritorMouseClicked

    private void TblEscritorKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TblEscritorKeyReleased

    }//GEN-LAST:event_TblEscritorKeyReleased

    private void btnEliminar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminar1ActionPerformed
        if (TblEscritor.getSelectedRowCount() > 0) {
            Escritor es = new Escritor();
            EscritoresDAO esDAO = new EscritoresDAO();
            int selectedRow = TblEscritor.getSelectedRow();
            es.setIdEscritor(Integer.parseInt(TblEscritor.getValueAt(selectedRow, 0).toString()));
            
            int response = JOptionPane.showConfirmDialog(null, "¿Desea eliminar el escritor?", "Eliminar", JOptionPane.OK_CANCEL_OPTION, JOptionPane.WARNING_MESSAGE);
            if (response == JOptionPane.YES_OPTION) {
                esDAO.DeleteEscritor(es);
                carga();
            }
            if (response == JOptionPane.NO_OPTION) {
                repaint();

            }

        } else {
            JOptionPane.showMessageDialog(null, "Seleccione una fila", "Aviso", 1);
        }
    }//GEN-LAST:event_btnEliminar1ActionPerformed
    public JfrmMenu mainForm;
    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        if (TblEscritor.getSelectedRowCount() > 0) {

            
            JfrmEscritorCrud frmOp = new JfrmEscritorCrud();
            int selectedRow = TblEscritor.getSelectedRow();
            frmOp.txtIdEscritor1.setText(String.valueOf(TblEscritor.getValueAt(selectedRow, 0)));
            frmOp.Id = Integer.parseInt(String.valueOf(TblEscritor.getValueAt(selectedRow, 0)));
            frmOp.txtCodigoEscritor.setText(String.valueOf(TblEscritor.getValueAt(selectedRow, 1)));
            frmOp.txtNombreEscritor.setText(String.valueOf(TblEscritor.getValueAt(selectedRow, 2)));
            frmOp.txtApellidoEscritor.setText(String.valueOf(TblEscritor.getValueAt(selectedRow, 3)));
            frmOp.txtPaisEscritor.setText(String.valueOf(TblEscritor.getValueAt(selectedRow, 4)));
            frmOp.jdcFN.setDate((Date) TblEscritor.getValueAt(selectedRow, 5));
            frmOp.txtBiog.setText(String.valueOf(TblEscritor.getValueAt(selectedRow, 6)));
            frmOp.jpE = this;
            frmOp.lblesc.setText("Actualizar Escritor");
            //frmOp.mostrarImagen();
            frmOp.setVisible(true);

            //isSelect = false;
        } else {
            JOptionPane.showMessageDialog(null, "Seleccione una fila", "Aviso", 1);
        }

    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnBusquedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBusquedaActionPerformed
        
    }//GEN-LAST:event_btnBusquedaActionPerformed

    private void btnBusquedaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBusquedaMouseEntered
        btnBusqueda.setBackground(new Color(75, 163, 252));
    }//GEN-LAST:event_btnBusquedaMouseEntered

    private void btnBusquedaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBusquedaMouseExited
        btnBusqueda.setBackground(new Color(41, 50, 65));
    }//GEN-LAST:event_btnBusquedaMouseExited

    private void btnBusquedaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBusquedaMousePressed
        btnBusqueda.setBackground(new Color(75, 163, 252));
    }//GEN-LAST:event_btnBusquedaMousePressed

    private void btnBusquedaMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBusquedaMouseReleased
        btnBusqueda.setBackground(new Color(41, 50, 65));
    }//GEN-LAST:event_btnBusquedaMouseReleased

    private void btnNuevoEscritorMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNuevoEscritorMouseEntered
        btnNuevoEscritor.setBackground(new Color(75, 163, 252));
    }//GEN-LAST:event_btnNuevoEscritorMouseEntered

    private void btnNuevoEscritorMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNuevoEscritorMouseExited
        btnNuevoEscritor.setBackground(new Color(0, 153, 51));
    }//GEN-LAST:event_btnNuevoEscritorMouseExited

    private void btnNuevoEscritorMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNuevoEscritorMousePressed
        btnNuevoEscritor.setBackground(new Color(75, 163, 252));
    }//GEN-LAST:event_btnNuevoEscritorMousePressed

    private void btnNuevoEscritorMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNuevoEscritorMouseReleased
        btnNuevoEscritor.setBackground(new Color(0, 153, 51));
    }//GEN-LAST:event_btnNuevoEscritorMouseReleased

    private void btnUpdateMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUpdateMouseEntered
         btnUpdate.setBackground(new Color(75, 163, 252));
    }//GEN-LAST:event_btnUpdateMouseEntered

    private void btnUpdateMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUpdateMouseExited
        btnUpdate.setBackground(new Color(238,108,77));
    }//GEN-LAST:event_btnUpdateMouseExited

    private void btnUpdateMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUpdateMousePressed
        btnUpdate.setBackground(new Color(75, 163, 252));
    }//GEN-LAST:event_btnUpdateMousePressed

    private void btnUpdateMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUpdateMouseReleased
        btnUpdate.setBackground(new Color(238,108,77));
    }//GEN-LAST:event_btnUpdateMouseReleased

    private void btnEliminar1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminar1MouseEntered
         btnEliminar1.setBackground(new Color(75, 163, 252));
    }//GEN-LAST:event_btnEliminar1MouseEntered

    private void btnEliminar1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminar1MouseExited
         btnEliminar1.setBackground(new Color(255,51,51));
    }//GEN-LAST:event_btnEliminar1MouseExited

    private void btnEliminar1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminar1MousePressed
        btnEliminar1.setBackground(new Color(75, 163, 252));
    }//GEN-LAST:event_btnEliminar1MousePressed

    private void btnEliminar1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminar1MouseReleased
         btnEliminar1.setBackground(new Color(255,51,51));
    }//GEN-LAST:event_btnEliminar1MouseReleased

    private void txtBusqEsKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBusqEsKeyPressed
        // TODO add your handling code here:
        cargaBusq();
    }//GEN-LAST:event_txtBusqEsKeyPressed

    public boolean isSelect = false;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TblEscritor;
    private javax.swing.JButton btnBusqueda;
    private javax.swing.JButton btnEliminar1;
    private javax.swing.JButton btnNuevoEscritor;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTextField txtBusqEs;
    // End of variables declaration//GEN-END:variables
}
