/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.alejandro.library_systemnuevo;

import Beans.Lectores;
import Entidades.Lector;
import java.util.ArrayList;
import java.util.Iterator;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author wilian
 */
public class JpLector extends javax.swing.JPanel {

    /**
     * Creates new form JpLector
     */
    public JpLector() {
        initComponents();
        carga();
    }

     public void carga() {
        String titulos[] = {"Id", "Codigo", "Nombre", "Apellido", "Edad", "Direccion", "Telefono"};
        //Ejemplosdearreglos
        Double numero[] = new Double[7];
        DefaultTableModel df = new DefaultTableModel(null, titulos);

        Lectores es = new Lectores();
        ArrayList<Lector> listar = es.ListaLector();

        Iterator iterador = listar.iterator();
        Object fila[] = new Object[7];

        while (iterador.hasNext()) {
            //CASTEAR
            Lector estBucle = (Lector) iterador.next();
            fila[0] = estBucle.getIdLector();
            fila[1] = estBucle.getCodigoLector();
            fila[2] = estBucle.getNombre_Lector();
            fila[3] = estBucle.getApellido_Lector();
            fila[4] = estBucle.getEdad();
            fila[5] = estBucle.getDireccion();
            fila[6] = estBucle.getTelefono();
            df.addRow(fila);
        }
        TblLector.setModel(df);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnNuevoLector = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TblLector = new javax.swing.JTable();
        btnEliminar = new javax.swing.JButton();
        btnActualizar1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setText("GESTIÓN DE LECTORES");

        btnNuevoLector.setText("Nuevo");
        btnNuevoLector.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoLectorActionPerformed(evt);
            }
        });

        TblLector.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        TblLector.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        TblLector.setGridColor(new java.awt.Color(0, 0, 0));
        TblLector.setSelectionBackground(new java.awt.Color(161, 220, 173));
        jScrollPane1.setViewportView(TblLector);

        btnEliminar.setBackground(java.awt.Color.blue);
        btnEliminar.setFont(new java.awt.Font("Roboto Bk", 0, 14)); // NOI18N
        btnEliminar.setForeground(new java.awt.Color(254, 254, 255));
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnActualizar1.setBackground(java.awt.Color.blue);
        btnActualizar1.setFont(new java.awt.Font("Roboto Bk", 0, 14)); // NOI18N
        btnActualizar1.setForeground(new java.awt.Color(254, 254, 255));
        btnActualizar1.setText("Actualizar");
        btnActualizar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizar1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnActualizar1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnNuevoLector, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1010, Short.MAX_VALUE))))
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnNuevoLector, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 381, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnActualizar1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnNuevoLectorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoLectorActionPerformed
        new JfrmLectorCrud().setVisible(true);
    }//GEN-LAST:event_btnNuevoLectorActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
//
//        try{
//            if(isSelect==true){
//                Lectores lectorDao = new Lectores();
//
//                int Id = Integer.parseInt(txtIdLector.getText());
//
//                Lector lector = new Lector(Id);
//                lectorDao.DeleteLector(lector);
//                cargaLector();
//
//                isSelect = false;
//            }else{
//                JOptionPane.showMessageDialog(null,"No ha seleccionado ningun lector","Aviso",1);
//            }
//
//        }catch(Exception ex){
//            JOptionPane.showMessageDialog(null,"Ha ocurrido un error"+ex);
//        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnActualizar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizar1ActionPerformed
//        try{
//            if(isSelect==true){
//
//                Lectores editLect = new Lectores();
//                int idLector= Integer.parseInt(txtIdLector.getText());
//
//                String CodigoLector = txtCodigoLector.getText();
//                String Nombre_Lector = txtNombreLector.getText();
//                String Apellido_Lector = txtApellidoLector.getText();
//                String Edad=txtEdadLector.getText();
//                String Direccion = txtDireccionLector.getText();
//                String Telefono = txtTelefonoLector.getText();
//
//                int row = TblLector.getSelectedRow();
//
//                TblLector.setValueAt(CodigoLector, row, 1);
//                TblLector.setValueAt(Nombre_Lector, row, 2);
//                TblLector.setValueAt(Apellido_Lector, row, 3);
//                TblLector.setValueAt(Edad, row, 4);
//                TblLector.setValueAt(Direccion, row, 5);
//                TblLector.setValueAt(Telefono, row, 6);
//
//                Lector lct = new Lector(idLector, CodigoLector, Nombre_Lector,Apellido_Lector, Edad,Direccion,Telefono);
//                editLect.UpdateLector(lct);
//                LimpiarLector();
//                cargaLector();
//                isSelect = false;
//            }else{
//                JOptionPane.showMessageDialog(null,"Seleccione una fila","Aviso",1);
//            }
//        }catch(Exception ex){
//            JOptionPane.showMessageDialog(null,"Ha ocurrido otro error","Error",JOptionPane.ERROR_MESSAGE);
//
//        }
    }//GEN-LAST:event_btnActualizar1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TblLector;
    private javax.swing.JButton btnActualizar1;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnNuevoLector;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
