/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.alejandro.library_systemnuevo;

import DAO.PrestamosDAO;
import Entidades.Enums.prestamoType;
import Entidades.Prestamo;
import ViewModel.PrestamoVM;
import java.awt.Color;
import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import utilidades.GestionColumnas;
import utilidades.GestionEncabezadoTabla;

/**
 *
 * @author Vkaiido
 */
public class JpPrestamo extends javax.swing.JPanel {

    /**
     * Creates new form JpPrestamo
     */
    public JpPrestamo() {
        initComponents();
        carga();
    }

    public void carga() {
        String titulos[] = {"Id", "Lector", "Titulo Libro", "Fecha Prestamo", "Fecha Devolucion", "Devuelto",};
        Double numero[] = new Double[7];
        DefaultTableModel df = new DefaultTableModel(null, titulos);

        PrestamosDAO es = new PrestamosDAO();
        ArrayList<PrestamoVM> listar = es.ListaPrestamo();

        Iterator iterador = listar.iterator();
        Object fila[] = new Object[7];
        //CASTEAR
        while (iterador.hasNext()) {
            PrestamoVM estBucle = (PrestamoVM) iterador.next();
            
            if (estBucle.getReembolso_prestamo().name().equals("No")) {
                fila[0] = estBucle.getIdPrestamo();
                fila[1] = estBucle.getNombre_Lector();
                fila[2] = estBucle.getTitulo();
                fila[3] = estBucle.getFecha_Prestamo();
                fila[4] = estBucle.getFecha_Devolucion();
                fila[5] = estBucle.getReembolso_prestamo().name();
                df.addRow(fila);
            }
        }
        tblPrest.setModel(df);

        tblPrest.getTableHeader().setReorderingAllowed(false);
        tblPrest.setRowHeight(30);
        tblPrest.setGridColor(new java.awt.Color(0, 0, 0));

        //PERSONALIZAR ENCABEZADO
        JTableHeader jtableHeader = tblPrest.getTableHeader();
        jtableHeader.setDefaultRenderer(new GestionEncabezadoTabla());
        tblPrest.setTableHeader(jtableHeader);

        tblPrest.setDefaultRenderer(Object.class, new GestionColumnas());
    }

    public void carga2(int EdoDevolucion) {
        String titulos[] = {"Id", "Lector", "Titulo Libro", "Fecha Prestamo", "Fecha Devolucion", "Devuelto",};
        Double numero[] = new Double[7];
        DefaultTableModel df = new DefaultTableModel(null, titulos);

        PrestamosDAO es = new PrestamosDAO();
        ArrayList<PrestamoVM> listar = es.ListaPrestamo();

        Iterator iterador = listar.iterator();
        Object fila[] = new Object[7];
        //CASTEAR
        while (iterador.hasNext()) {
            PrestamoVM estBucle = (PrestamoVM) iterador.next();
            if (estBucle.getReembolso_prestamo().name().equals(String.valueOf(prestamoType.values()[EdoDevolucion]))) {
                fila[0] = estBucle.getIdPrestamo();
                fila[1] = estBucle.getNombre_Lector();
                fila[2] = estBucle.getTitulo();
                fila[3] = estBucle.getFecha_Prestamo();
                fila[4] = estBucle.getFecha_Devolucion();
                fila[5] = estBucle.getReembolso_prestamo().name();
                df.addRow(fila);
            }
        }
        tblPrest.setModel(df);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPrest = new javax.swing.JTable();
        btnActualizarPrestamo = new javax.swing.JButton();
        btnEliminarPrestamo = new javax.swing.JButton();
        btnNuevoPrestamo = new javax.swing.JButton();
        cmbEdo = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1050, 540));

        jLabel1.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(41, 50, 65));
        jLabel1.setText("GESTIÓN DE PRESTAMOS");

        tblPrest.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        tblPrest.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblPrest.setGridColor(new java.awt.Color(0, 0, 0));
        tblPrest.setSelectionBackground(new java.awt.Color(161, 220, 173));
        jScrollPane1.setViewportView(tblPrest);

        btnActualizarPrestamo.setBackground(new java.awt.Color(238, 108, 77));
        btnActualizarPrestamo.setForeground(new java.awt.Color(255, 255, 255));
        btnActualizarPrestamo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Update.png"))); // NOI18N
        btnActualizarPrestamo.setText("Actualizar");
        btnActualizarPrestamo.setContentAreaFilled(false);
        btnActualizarPrestamo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnActualizarPrestamo.setOpaque(true);
        btnActualizarPrestamo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnActualizarPrestamoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnActualizarPrestamoMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnActualizarPrestamoMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnActualizarPrestamoMouseReleased(evt);
            }
        });
        btnActualizarPrestamo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarPrestamoActionPerformed(evt);
            }
        });

        btnEliminarPrestamo.setBackground(new java.awt.Color(255, 51, 51));
        btnEliminarPrestamo.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminarPrestamo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/trash (1).png"))); // NOI18N
        btnEliminarPrestamo.setText("Eliminar");
        btnEliminarPrestamo.setContentAreaFilled(false);
        btnEliminarPrestamo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEliminarPrestamo.setOpaque(true);
        btnEliminarPrestamo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnEliminarPrestamoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnEliminarPrestamoMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnEliminarPrestamoMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnEliminarPrestamoMouseReleased(evt);
            }
        });
        btnEliminarPrestamo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarPrestamoActionPerformed(evt);
            }
        });

        btnNuevoPrestamo.setBackground(new java.awt.Color(0, 153, 51));
        btnNuevoPrestamo.setForeground(new java.awt.Color(255, 255, 255));
        btnNuevoPrestamo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/new-file.png"))); // NOI18N
        btnNuevoPrestamo.setText("Nuevo prestamo");
        btnNuevoPrestamo.setContentAreaFilled(false);
        btnNuevoPrestamo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnNuevoPrestamo.setOpaque(true);
        btnNuevoPrestamo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnNuevoPrestamoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnNuevoPrestamoMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnNuevoPrestamoMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnNuevoPrestamoMouseReleased(evt);
            }
        });
        btnNuevoPrestamo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoPrestamoActionPerformed(evt);
            }
        });

        cmbEdo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sin Devolver", "Devuelto" }));
        cmbEdo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbEdoActionPerformed(evt);
            }
        });

        jLabel2.setText("Estado");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnActualizarPrestamo, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnEliminarPrestamo, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cmbEdo, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(51, 51, 51)
                                .addComponent(btnNuevoPrestamo))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1010, Short.MAX_VALUE))))
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmbEdo)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnNuevoPrestamo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 373, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEliminarPrestamo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnActualizarPrestamo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnActualizarPrestamoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarPrestamoActionPerformed
        if (tblPrest.getSelectedRowCount() > 0) {
            JfrmPrestamoCrud frm = new JfrmPrestamoCrud();

            int selectedRow = tblPrest.getSelectedRow();
            frm.txtIdPrestamo.setText(String.valueOf(tblPrest.getValueAt(selectedRow, 0)));
            frm.CmbFL.setSelectedItem(String.valueOf(tblPrest.getValueAt(selectedRow, 1)));
            frm.CmbFLib.setSelectedItem(String.valueOf(tblPrest.getValueAt(selectedRow, 2)));
            frm.JDCFprestamo.setDate((Date) tblPrest.getValueAt(selectedRow, 3));
            frm.JDCFDev.setDate((Date) tblPrest.getValueAt(selectedRow, 4));
            frm.cmbDevuelto.setSelectedItem(String.valueOf(tblPrest.getValueAt(selectedRow, 5)));
            frm.lblInCl.setText("Actualizar Solicitud de Prestamo");

            frm.jpP = this;
            frm.setVisible(true);

        } else {
            JOptionPane.showMessageDialog(null, "Seleccione una fila", "Aviso", 1);
        }
    }//GEN-LAST:event_btnActualizarPrestamoActionPerformed

    private void btnEliminarPrestamoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarPrestamoActionPerformed
        if (tblPrest.getSelectedRowCount() > 0) {
            Prestamo prees = new Prestamo();
            PrestamosDAO prDAO = new PrestamosDAO();
            int selectedRow = tblPrest.getSelectedRow();
            prees.setIdPrestamo(Integer.parseInt(tblPrest.getValueAt(selectedRow, 0).toString()));
 int response = JOptionPane.showConfirmDialog(null, "¿Desea eliminar la solicitud de prestamo?", "Eliminar", JOptionPane.OK_CANCEL_OPTION, JOptionPane.WARNING_MESSAGE);
            if (response == JOptionPane.YES_OPTION) {
            prDAO.DeletePrestamo(prees);
            carga();
            }
            if (response == JOptionPane.NO_OPTION) {
                repaint();

            }
        } else {
            JOptionPane.showMessageDialog(null, "Seleccione una fila", "Aviso", 1);
        }
    }//GEN-LAST:event_btnEliminarPrestamoActionPerformed

    private void btnNuevoPrestamoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoPrestamoActionPerformed
        JfrmPrestamoCrud frm = new JfrmPrestamoCrud();
        frm.jpP = this;
            frm.setVisible(true);
    }//GEN-LAST:event_btnNuevoPrestamoActionPerformed


    private void cmbEdoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbEdoActionPerformed

        carga2(cmbEdo.getSelectedIndex());
    }//GEN-LAST:event_cmbEdoActionPerformed

    private void btnNuevoPrestamoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNuevoPrestamoMouseEntered
        btnNuevoPrestamo.setBackground(new Color(75, 163, 252));
    }//GEN-LAST:event_btnNuevoPrestamoMouseEntered

    private void btnNuevoPrestamoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNuevoPrestamoMouseExited
        btnNuevoPrestamo.setBackground(new Color(0, 153, 51));
    }//GEN-LAST:event_btnNuevoPrestamoMouseExited

    private void btnNuevoPrestamoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNuevoPrestamoMousePressed
        btnNuevoPrestamo.setBackground(new Color(75, 163, 252));
    }//GEN-LAST:event_btnNuevoPrestamoMousePressed

    private void btnNuevoPrestamoMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNuevoPrestamoMouseReleased
        btnNuevoPrestamo.setBackground(new Color(0, 153, 51));
    }//GEN-LAST:event_btnNuevoPrestamoMouseReleased

    private void btnActualizarPrestamoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnActualizarPrestamoMouseEntered
        btnActualizarPrestamo.setBackground(new Color(75, 163, 252));
    }//GEN-LAST:event_btnActualizarPrestamoMouseEntered

    private void btnActualizarPrestamoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnActualizarPrestamoMouseExited
        btnActualizarPrestamo.setBackground(new Color(238, 108, 77));
    }//GEN-LAST:event_btnActualizarPrestamoMouseExited

    private void btnActualizarPrestamoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnActualizarPrestamoMousePressed
        btnActualizarPrestamo.setBackground(new Color(75, 163, 252));
    }//GEN-LAST:event_btnActualizarPrestamoMousePressed

    private void btnActualizarPrestamoMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnActualizarPrestamoMouseReleased
        btnActualizarPrestamo.setBackground(new Color(238, 108, 77));
    }//GEN-LAST:event_btnActualizarPrestamoMouseReleased

    private void btnEliminarPrestamoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarPrestamoMouseEntered
        btnEliminarPrestamo.setBackground(new Color(75, 163, 252));
    }//GEN-LAST:event_btnEliminarPrestamoMouseEntered

    private void btnEliminarPrestamoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarPrestamoMouseExited
        btnEliminarPrestamo.setBackground(new Color(255, 51, 51));
    }//GEN-LAST:event_btnEliminarPrestamoMouseExited

    private void btnEliminarPrestamoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarPrestamoMousePressed
        btnEliminarPrestamo.setBackground(new Color(75, 163, 252));
    }//GEN-LAST:event_btnEliminarPrestamoMousePressed

    private void btnEliminarPrestamoMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarPrestamoMouseReleased
        btnEliminarPrestamo.setBackground(new Color(255, 51, 51));
    }//GEN-LAST:event_btnEliminarPrestamoMouseReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizarPrestamo;
    private javax.swing.JButton btnEliminarPrestamo;
    private javax.swing.JButton btnNuevoPrestamo;
    private javax.swing.JComboBox<String> cmbEdo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblPrest;
    // End of variables declaration//GEN-END:variables
}
