/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.alejandro.library_systemnuevo;

import DAO.*;
import Entidades.*;
import java.awt.Color;
import java.awt.event.KeyEvent;
//import java.text.DecimalFormat;
//import java.time.LocalDateTime;
import java.util.*;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import utilidades.GestionColumnas;
import utilidades.GestionEncabezadoTabla;

/**
 *
 * @author Vkaiido
 */
public class JpVentas extends javax.swing.JPanel {

    DefaultTableModel model = new DefaultTableModel();
    //DecimalFormat formato=new DecimalFormat("#.##");
    Date fecha = new Date();
    //int IdCliente[];
    //int IdLibro[];
    int librofk;
    Libro lb = new Libro();

    int idc;
    int idlb;

    /**
     * Creates new form JPVentas
     */
    public void cargar() {

        tblVenta.getTableHeader().setReorderingAllowed(false);
        tblVenta.setRowHeight(30);
        tblVenta.setGridColor(new java.awt.Color(0, 0, 0));

        //PERSONALIZAR ENCABEZADO
        JTableHeader jtableHeader = tblVenta.getTableHeader();
        jtableHeader.setDefaultRenderer(new GestionEncabezadoTabla());
        tblVenta.setTableHeader(jtableHeader);

        tblVenta.setDefaultRenderer(Object.class, new GestionColumnas());

    }

    public JpVentas() {
        initComponents();
        txtNumeroDoc.setText("21112000");
        fecha = Calendar.getInstance().getTime();
        //FiltroCliente(Busqueda);
        jdcFecha.setDate(fecha);
        initId();
        //txtStock.setText(String.valueOf(lb));
        tblVenta.getColumnModel().getColumn(1).setPreferredWidth(250);
    }

    private void initId() {
        VentasDAO vt = new VentasDAO();
        int ID = vt.idVenta();
        txtIDVENTA.setText(String.valueOf(ID + 1));

    }

    private void limpiar() {
        txtCliente.setText("");
        txtPrecio.setText("");
        txtCant.setText("");
        txtStock.setText("");
        txtImpuesto.setText("");
        txtTotal.setText("");
        //cmbDui.setSelectedIndex(-1);
        txtClinte.setText("");
        //cmbLibro.setSelectedIndex(-1);
        txtclib.setText("");
        txtLibro.setText("");

    }

//    private void FiltroLibro(String Busqueda) {
//        cmbLibro.removeAllItems();
//        LibrosDAO libFiltro = new LibrosDAO();
//        IdLibro = new int[libFiltro.FiltroLibro(Busqueda).size()];
//
//        int Indice = 0;
//        for (var libro : libFiltro.FiltroLibro(Busqueda)) {
//            cmbLibro.addItem(libro.getCodigo_Libro());
//            txtLibro.setText(libro.getTitulo());
//            IdLibro[Indice] = libro.getIdLibro();
//            txtStock.setText(String.valueOf(libro.getCantidad()));
//            txtPrecio.setText(String.valueOf(libro.getPrecio()));
//            librofk = libro.getIdLibro();
//            Indice++;
//        }
//
//    }
    //BuscarClientes
//    private void FiltroCliente(String Busqueda) {
//        cmbDui.removeAllItems();
//        ClientesDao clFiltro = new ClientesDao();
//        IdCliente = new int[clFiltro.FiltroClientes(Busqueda).size()];
//
//        int Indice = 0;
//        for (var cliente : clFiltro.FiltroClientes(Busqueda)) {
//            cmbDui.addItem(cliente.getNombre_cliente());
//            txtCliente.setText(cliente.getDocumento_cliente());
//            IdCliente[Indice] = cliente.getId_cliente();
//            Indice++;
//        }
//    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        combobox1 = new Others.ComboBox();
        combobox2 = new Others.ComboBox();
        combobox3 = new Others.ComboBox();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtNumeroDoc = new javax.swing.JTextField();
        txtIDVENTA = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        txtCCliente = new javax.swing.JLabel();
        btnMC = new javax.swing.JButton();
        txtCCliente1 = new javax.swing.JLabel();
        txtCliente = new javax.swing.JTextField();
        txtCCliente2 = new javax.swing.JLabel();
        btnML = new javax.swing.JButton();
        txtCCliente3 = new javax.swing.JLabel();
        txtLibro = new javax.swing.JTextField();
        txtCCliente4 = new javax.swing.JLabel();
        txtPrecio = new javax.swing.JTextField();
        txtCCliente5 = new javax.swing.JLabel();
        txtCant = new javax.swing.JTextField();
        txtCCliente6 = new javax.swing.JLabel();
        txtStock = new javax.swing.JTextField();
        txtCCliente7 = new javax.swing.JLabel();
        jdcFecha = new com.toedter.calendar.JDateChooser();
        txtCCliente8 = new javax.swing.JLabel();
        txtClinte = new javax.swing.JTextField();
        txtclib = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblVenta = new javax.swing.JTable();
        BtnCancelar = new javax.swing.JButton();
        btnAgregarVenta = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtTotal = new javax.swing.JTextField();
        txtImpuesto = new javax.swing.JTextField();
        btnADD = new javax.swing.JButton();
        BtnBorrar = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1050, 100));

        jLabel1.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("La casa del libro");

        jLabel3.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        jLabel4.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Numero de documento");

        txtNumeroDoc.setEditable(false);

        txtIDVENTA.setEditable(false);
        txtIDVENTA.setOpaque(true);
        txtIDVENTA.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtIDVENTAKeyTyped(evt);
            }
        });

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Id Venta");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtIDVENTA, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(139, 139, 139))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtNumeroDoc, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(452, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtIDVENTA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNumeroDoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        txtCCliente.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        txtCCliente.setText("CLIENTE :");

        btnMC.setBackground(new java.awt.Color(41, 50, 65));
        btnMC.setForeground(new java.awt.Color(255, 255, 255));
        btnMC.setText("Buscar");
        btnMC.setContentAreaFilled(false);
        btnMC.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMC.setOpaque(true);
        btnMC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnMCMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnMCMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnMCMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnMCMouseReleased(evt);
            }
        });
        btnMC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMCActionPerformed(evt);
            }
        });

        txtCCliente1.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        txtCCliente1.setText("DUI CLIENTE:");

        txtCliente.setEditable(false);
        txtCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtClienteKeyTyped(evt);
            }
        });

        txtCCliente2.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        txtCCliente2.setText("CODIGO LIBRO");

        btnML.setBackground(new java.awt.Color(41, 50, 65));
        btnML.setForeground(new java.awt.Color(255, 255, 255));
        btnML.setText("Buscar");
        btnML.setContentAreaFilled(false);
        btnML.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnML.setOpaque(true);
        btnML.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnMLMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnMLMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnMLMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnMLMouseReleased(evt);
            }
        });
        btnML.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMLActionPerformed(evt);
            }
        });

        txtCCliente3.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        txtCCliente3.setText("LIBRO:");

        txtLibro.setEditable(false);

        txtCCliente4.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        txtCCliente4.setText("PRECIO:");

        txtPrecio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPrecioKeyTyped(evt);
            }
        });

        txtCCliente5.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        txtCCliente5.setText("CANTIDAD:");
        txtCCliente5.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        txtCant.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCantKeyTyped(evt);
            }
        });

        txtCCliente6.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        txtCCliente6.setText("INVENTARIO:");
        txtCCliente6.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        txtStock.setEditable(false);

        txtCCliente7.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        txtCCliente7.setText("FECHA:");
        txtCCliente7.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        txtCCliente8.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        txtCCliente8.setText("$");

        txtClinte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtClinteActionPerformed(evt);
            }
        });
        txtClinte.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtClinteKeyPressed(evt);
            }
        });

        txtclib.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtclibActionPerformed(evt);
            }
        });
        txtclib.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtclibKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtCCliente2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtCCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(txtCCliente4, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtCCliente8)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52)
                        .addComponent(txtCCliente5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCant, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(txtclib)
                        .addComponent(txtClinte, javax.swing.GroupLayout.DEFAULT_SIZE, 331, Short.MAX_VALUE)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(btnMC))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                            .addGap(12, 12, 12)
                            .addComponent(btnML)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(txtCCliente6, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtCCliente1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtCCliente3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(23, 23, 23)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCliente)
                            .addComponent(txtLibro)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(txtStock, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(txtCCliente7, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jdcFecha, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE)))
                .addGap(20, 20, 20))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMC)
                    .addComponent(txtCCliente1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtClinte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCCliente2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnML)
                    .addComponent(txtCCliente3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtLibro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtclib, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtCCliente4, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtStock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtCCliente6, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtCant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtCCliente5, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtCCliente7, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtCCliente8))
                    .addComponent(jdcFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        tblVenta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id_Libro", "Libro", "Cantidad", "Precio", "impuesto", "Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblVenta.setPreferredSize(new java.awt.Dimension(1030, 240));
        tblVenta.addHierarchyListener(new java.awt.event.HierarchyListener() {
            public void hierarchyChanged(java.awt.event.HierarchyEvent evt) {
                tblVentaHierarchyChanged(evt);
            }
        });
        tblVenta.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                tblVentaComponentShown(evt);
            }
        });
        jScrollPane1.setViewportView(tblVenta);

        BtnCancelar.setBackground(new java.awt.Color(255, 51, 51));
        BtnCancelar.setForeground(new java.awt.Color(255, 255, 255));
        BtnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/error.png"))); // NOI18N
        BtnCancelar.setText("Cancelar Venta");
        BtnCancelar.setContentAreaFilled(false);
        BtnCancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnCancelar.setOpaque(true);
        BtnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCancelarActionPerformed(evt);
            }
        });

        btnAgregarVenta.setBackground(new java.awt.Color(0, 153, 51));
        btnAgregarVenta.setForeground(new java.awt.Color(255, 255, 255));
        btnAgregarVenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cashier-machine.png"))); // NOI18N
        btnAgregarVenta.setText("Agregar Venta");
        btnAgregarVenta.setContentAreaFilled(false);
        btnAgregarVenta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAgregarVenta.setOpaque(true);
        btnAgregarVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarVentaActionPerformed(evt);
            }
        });

        jLabel5.setText("Impuesto");

        jLabel6.setText("Total");

        txtTotal.setEditable(false);

        txtImpuesto.setEditable(false);
        txtImpuesto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtImpuestoActionPerformed(evt);
            }
        });

        btnADD.setBackground(new java.awt.Color(0, 153, 51));
        btnADD.setForeground(new java.awt.Color(255, 255, 255));
        btnADD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/addlbr.png"))); // NOI18N
        btnADD.setText("Agregar Libro");
        btnADD.setContentAreaFilled(false);
        btnADD.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnADD.setOpaque(true);
        btnADD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnADDMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnADDMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnADDMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnADDMouseReleased(evt);
            }
        });
        btnADD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnADDActionPerformed(evt);
            }
        });
        btnADD.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                btnADDKeyTyped(evt);
            }
        });

        BtnBorrar.setBackground(new java.awt.Color(255, 51, 51));
        BtnBorrar.setForeground(new java.awt.Color(255, 255, 255));
        BtnBorrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/delLib.png"))); // NOI18N
        BtnBorrar.setText("Eliminar Libro");
        BtnBorrar.setContentAreaFilled(false);
        BtnBorrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnBorrar.setOpaque(true);
        BtnBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBorrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(btnAgregarVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(BtnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(389, 389, 389)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtImpuesto, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(btnADD)
                        .addGap(32, 32, 32)
                        .addComponent(BtnBorrar))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1013, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnADD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BtnBorrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtImpuesto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAgregarVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BtnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(14, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(5, 5, 5))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 1056, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    private void eliminar() {
        int fil;
        if (model.getRowCount() > 0) {
            if (tblVenta.getSelectedRow() != -1) {
                fil = tblVenta.getSelectedRow();
                model.removeRow(fil);
                calcularTotal();
            } else {
                JOptionPane.showMessageDialog(null, "Seleccione Una Fila");
            }
        } else {
            JOptionPane.showMessageDialog(null, "No hay Filas en la Tabla");
        }
    }
    private void BtnBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBorrarActionPerformed
        eliminar();
    }//GEN-LAST:event_BtnBorrarActionPerformed

    private void btnMCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMCActionPerformed
        //FiltroCliente(cmbDui.getSelectedItem().toString());
        JfrmAgCliente formulario = new JfrmAgCliente();
        formulario.setVisible(true);
    }//GEN-LAST:event_btnMCActionPerformed

    private void btnMLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMLActionPerformed
        JfrmAgLibro formulario = new JfrmAgLibro();
        formulario.setVisible(true);
    }//GEN-LAST:event_btnMLActionPerformed


    private void txtCantKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCantKeyTyped
        char caracter = evt.getKeyChar();
        if (caracter < '0' || caracter > '9') {
            evt.consume();
        }

        char TPresionada = evt.getKeyChar();

        if (TPresionada == KeyEvent.VK_ENTER) {
            btnADD.doClick();
        }
    }//GEN-LAST:event_txtCantKeyTyped

    private double redondear(double num) {
        return Math.rint(num * 100) / 100;
    }

    void calcularTotal() {

        double subtotal = 0;
        double sumaImpuesto = 0;
        for (int i = 0; i < tblVenta.getRowCount(); i++) {

            double impuesto = Double.parseDouble(tblVenta.getValueAt(i, 4).toString());
            double total = Double.parseDouble(tblVenta.getValueAt(i, 5).toString());
            sumaImpuesto += impuesto;
            subtotal += total;

        }

        txtImpuesto.setText(String.valueOf(redondear(sumaImpuesto)));
        double total = subtotal + sumaImpuesto;
        txtTotal.setText(String.valueOf(redondear(total)));
    }

    public void cmmq() {
        try {
            int numero1 = Integer.parseInt(txtStock.getText());
            int numero2 = Integer.parseInt(txtCant.getText());

            // Comparar los números
            if (numero1 >= numero2) {

            } else {

                System.out.println("La cantidad ingresada excede el stock");
            }
        } catch (NumberFormatException e) {
            // Manejo de error si los valores no son números válidos
            System.out.println("Los valores ingresados no son números válidos");
        }
    }

    private void btnADDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnADDActionPerformed

        if (txtPrecio.getText().equals("") || txtCant.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "HAY CAMPOS VACIOS");

        } else {
            if (Integer.parseInt(txtStock.getText()) > 0) {
                try {
                    int stock = Integer.parseInt(txtStock.getText());
                    int cantidadd = Integer.parseInt(txtCant.getText());

                    // Comparar los números
                    if (stock >= cantidadd) {
                        model = (DefaultTableModel) tblVenta.getModel();
                        String rowData[] = new String[6];
                        //rowData[0] = cmbLibro.getSelectedItem().toString();
                        rowData[0] = String.valueOf(idlb);

                        rowData[1] = txtLibro.getText();
                        rowData[2] = txtCant.getText();
                        rowData[3] = txtPrecio.getText();
                        int cantidad = Integer.parseInt(txtCant.getText());
                        double precio = Double.parseDouble(txtPrecio.getText());
                        double totallb = cantidad * precio;
                        rowData[4] = String.valueOf(redondear(totallb * 0.13));
                        rowData[5] = String.valueOf(redondear(totallb));

                        model.addRow(rowData);

                        calcularTotal();

                    } else {

                        JOptionPane.showMessageDialog(null, "Inventario Insuficiente");
                    }
                } catch (NumberFormatException e) {
                    
                    JOptionPane.showMessageDialog(null, "Formato Invalido");
                }

            } else {
                JOptionPane.showMessageDialog(null, "El articulo seleccionado no tiene existencias");
            }
        }


    }//GEN-LAST:event_btnADDActionPerformed

    private void txtImpuestoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtImpuestoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtImpuestoActionPerformed

    private void txtPrecioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPrecioKeyTyped
        if (!Character.isDigit(evt.getKeyChar()) && evt.getKeyChar() != '.') {
            evt.consume();
        }

        if (evt.getKeyChar() == '.' && txtPrecio.getText().contains(".")) {
            evt.consume();
        }

        char TPresionada = evt.getKeyChar();

        if (TPresionada == KeyEvent.VK_ENTER) {
            btnADD.doClick();
        }
    }//GEN-LAST:event_txtPrecioKeyTyped

    private void guardarVenta() {
        //int idVenta=0;
        venttas ventas = new venttas();
        VentasDAO ventasDao = new VentasDAO();

        //ventas.setId_cliente_fk(IdCliente[cmbDui.getSelectedIndex()]);
        ventas.setId_cliente_fk(idc);
        ventas.setFecha_venta(fecha);
        ventas.setNumero_comprobante(txtNumeroDoc.getText());
        ventas.setId_ventas(Integer.parseInt(txtIDVENTA.getText()));

        ventasDao.addVentas(ventas);

    }

    private void guardarDetalle() {
        detalleVentas dtv = new detalleVentas();
        VentasDAO ventasDao = new VentasDAO();

        int IDVENTA = Integer.parseInt(txtIDVENTA.getText());
        for (int i = 0; i < tblVenta.getRowCount(); i++) {
            dtv.setIdVenta(IDVENTA);

            //dtv.setIdlibro(IdLibro[cmbLibro.getSelectedIndex()]);
            //dtv.setIdlibro(librofk);
            dtv.setIdlibro(Integer.parseInt(tblVenta.getValueAt(i, 0).toString()));
            dtv.setCantidadVenta(Integer.parseInt(tblVenta.getValueAt(i, 2).toString()));

            dtv.setPrecioVenta(Double.parseDouble(tblVenta.getValueAt(i, 3).toString()));
            dtv.setDecuentoVenta(0);
            dtv.setImpuestoVenta(Double.parseDouble(tblVenta.getValueAt(i, 4).toString()));

            ventasDao.addDetalleVenta(dtv);

        }

    }


    private void btnAgregarVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarVentaActionPerformed

        if (idc != 0 && idlb != 0) {
            guardarVenta();
            guardarDetalle();
            //JOptionPane.showMessageDialog(null, "Detalle de ventas agregadas");
            limpiar();
            clearTable();
        } else {
            JOptionPane.showMessageDialog(null, "Llene todos los campos");
        }

    }//GEN-LAST:event_btnAgregarVentaActionPerformed
    public void clearTable() {
        tblVenta.selectAll();
        int filas[] = tblVenta.getSelectedRows();
        int indice = filas.length - 1;
        for (int i = 0; i < filas.length; i++) {
            model.removeRow(indice);
            indice--;
        }
    }


    private void BtnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCancelarActionPerformed
        clearTable();
        limpiar();
    }//GEN-LAST:event_BtnCancelarActionPerformed

    private void txtIDVENTAKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIDVENTAKeyTyped

    }//GEN-LAST:event_txtIDVENTAKeyTyped

    private void txtClienteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtClienteKeyTyped
        if (txtNumeroDoc.getText().length() >= 1) {
            evt.consume();
        }
    }//GEN-LAST:event_txtClienteKeyTyped

    private void tblVentaComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_tblVentaComponentShown

    }//GEN-LAST:event_tblVentaComponentShown

    private void tblVentaHierarchyChanged(java.awt.event.HierarchyEvent evt) {//GEN-FIRST:event_tblVentaHierarchyChanged
        tblVenta.getTableHeader().setReorderingAllowed(false);
        tblVenta.setRowHeight(30);
        tblVenta.setGridColor(new java.awt.Color(0, 0, 0));

        //PERSONALIZAR ENCABEZADO
        JTableHeader jtableHeader = tblVenta.getTableHeader();
        jtableHeader.setDefaultRenderer(new GestionEncabezadoTabla());
        tblVenta.setTableHeader(jtableHeader);

        tblVenta.setDefaultRenderer(Object.class, new GestionColumnas());
    }//GEN-LAST:event_tblVentaHierarchyChanged

    private void btnMCMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMCMouseEntered
        btnMC.setBackground(new Color(240, 240, 240));
        btnMC.setForeground(new Color(0, 0, 0));
    }//GEN-LAST:event_btnMCMouseEntered

    private void btnMCMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMCMouseExited
        btnMC.setBackground(new Color(41, 50, 65));
        btnMC.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_btnMCMouseExited

    private void btnMCMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMCMousePressed
        btnMC.setBackground(new Color(240, 240, 240));
        btnMC.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_btnMCMousePressed

    private void btnMCMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMCMouseReleased
        btnMC.setBackground(new Color(41, 50, 65));
    }//GEN-LAST:event_btnMCMouseReleased

    private void btnMLMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMLMouseEntered
        //Abajo
        btnML.setBackground(new Color(240, 240, 240));
        btnML.setForeground(new Color(0, 0, 0));
    }//GEN-LAST:event_btnMLMouseEntered

    private void btnMLMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMLMouseExited
        btnML.setBackground(new Color(41, 50, 65));
        btnML.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_btnMLMouseExited

    private void btnMLMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMLMousePressed
        btnML.setBackground(new Color(240, 240, 240));
        btnML.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_btnMLMousePressed

    private void btnMLMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMLMouseReleased
        btnML.setBackground(new Color(41, 50, 65));
    }//GEN-LAST:event_btnMLMouseReleased

    private void btnADDMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnADDMouseEntered

    }//GEN-LAST:event_btnADDMouseEntered

    private void btnADDMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnADDMouseExited

    }//GEN-LAST:event_btnADDMouseExited

    private void btnADDMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnADDMousePressed

    }//GEN-LAST:event_btnADDMousePressed

    private void btnADDMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnADDMouseReleased

    }//GEN-LAST:event_btnADDMouseReleased

    private void btnADDKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnADDKeyTyped

    }//GEN-LAST:event_btnADDKeyTyped

    private void txtClinteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtClinteActionPerformed

    }//GEN-LAST:event_txtClinteActionPerformed

    private void txtClinteKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtClinteKeyPressed
        int keyCode = evt.getKeyCode();
        if (keyCode == KeyEvent.VK_ADD || keyCode == KeyEvent.VK_SPACE) {
            JfrmAgCliente formulario = new JfrmAgCliente();
            formulario.jpVent = this;
            formulario.setVisible(true);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_txtClinteKeyPressed

    private void txtclibActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtclibActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtclibActionPerformed

    private void txtclibKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtclibKeyPressed
        int keyCode = evt.getKeyCode();
        if (keyCode == KeyEvent.VK_ADD || keyCode == KeyEvent.VK_SPACE) {
            JfrmAgLibro formulario = new JfrmAgLibro();
            formulario.jpVent = this;
            formulario.setVisible(true);
        }
    }//GEN-LAST:event_txtclibKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnBorrar;
    private javax.swing.JButton BtnCancelar;
    private javax.swing.JButton btnADD;
    private javax.swing.JButton btnAgregarVenta;
    private javax.swing.JButton btnMC;
    private javax.swing.JButton btnML;
    private javax.swing.ButtonGroup buttonGroup1;
    private Others.ComboBox combobox1;
    private Others.ComboBox combobox2;
    private Others.ComboBox combobox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private com.toedter.calendar.JDateChooser jdcFecha;
    private javax.swing.JTable tblVenta;
    private javax.swing.JLabel txtCCliente;
    private javax.swing.JLabel txtCCliente1;
    private javax.swing.JLabel txtCCliente2;
    private javax.swing.JLabel txtCCliente3;
    private javax.swing.JLabel txtCCliente4;
    private javax.swing.JLabel txtCCliente5;
    private javax.swing.JLabel txtCCliente6;
    private javax.swing.JLabel txtCCliente7;
    private javax.swing.JLabel txtCCliente8;
    private javax.swing.JTextField txtCant;
    public javax.swing.JTextField txtCliente;
    public javax.swing.JTextField txtClinte;
    private javax.swing.JTextField txtIDVENTA;
    private javax.swing.JTextField txtImpuesto;
    public javax.swing.JTextField txtLibro;
    private javax.swing.JTextField txtNumeroDoc;
    public javax.swing.JTextField txtPrecio;
    public javax.swing.JTextField txtStock;
    private javax.swing.JTextField txtTotal;
    public javax.swing.JTextField txtclib;
    // End of variables declaration//GEN-END:variables
}
